from pathlib import Path
import hashlib,json
p=Path(__file__).resolve().parent
items={
'GOAL':'Stage one coherent local-observable approximation theorem with independent geometry and actual Wilson-loop certificates. No repository edits are made.',
'ASSUMPTIONS_AND_IMPORTS':'Supplied compact Hamiltonian29 and complete Peter-Weyl cutoff32; a>0,v>=0; bounded local observable; finite local form energy; conditioned cutoff preparation with explicit p. Strong-topology propagation uses primary1410.8174 Proposition2.1/Lemma2.2 and support recursion. No gap34 premise, native compiler, deterministic all-input encoder or physical time selection.',
'ROUTE_PORTFOLIO':'Primary independently derived face-chain propagation and exponential boundary bound. Root independently derived sharper integrated Theta tail and expectation normalization. Canonical body is the reviewed root proof; independent primary proof and all historical clarifications remain evidence, not duplicate theorem claims.',
'NO_GO_LEDGER':'An actual physical Wilson-loop state reduces to I9/9 on one fundamental matrix block: boundary-singlet projection loses it with probability1. Finite local energy does not ensure positive cutoff preparation if E>=g. Arbitrary volume-varying interactions need not have a common infinite dynamics. Trace norm is distinguished from half trace norm. These scoped corrections/adverse cases are preserved.',
'LITERATURE_BRIDGES':'Nachtergaele and Sims1410.8174 is directly inspected primary literature for strong operator calculus with unbounded onsite terms. General Lieb-Robinson theory and projected Duhamel are established mathematical methods; no generic-prior-art novelty is claimed. The source supplies explicit constants and native-model boundary-charge qualification.',
'ARTIFACT_PLAN':'Retrospective port: one canonical note, standalone geometry primary29 checks and independent Schmidt/tail helper28 checks. All original source proofs/preregs/raw/checkers/reviews copied. Actual JSON and default stdout receipts are scratch runs, not repository cache claims. Integration must execute and stage real canonical .txt caches.',
'CLAIM_STATUS_CERTIFICATE':'Type bounded_theorem, conditional-support. One source claim, depending on29 and32. Local-probe expectation bound under finite local energy, not full-volume state or all-input diamond approximation. Finite storage is not gate compilation.',
'REVIEW_HISTORY':'Root897efdbc proof independently reviewed by primary68a7a098. Primary1244 proof reviewed by root7acbf701 and native; native requested trace-norm terminology and explicit fixed infinite-family clarification. Current primary f062934 preserves both corrections without changing finite constants. This port is by primary and has no self-independent-port-PASS claim.',
'PR_BACKLOG':'Pending root canonical review, isolated integration, actual staged caches and required graph/pipeline/strict/readiness. Stack placement after34 is review ordering, not a scientific gap-theorem dependency.',
'TRACE_GATE':'Canonical source imports29 compact dynamics and32 form-energy cutoff. Actual finite geometry supports propagation indexing; actual loop/Haar-derived Schmidt algebra supports the boundary adverse example. All-orders/domain arguments remain analytical.',
'STATUS':'READY FOR ROOT PORT REVIEW. Canonical root proof body verbatim; all original scientific JSON fields and check lists exactly unchanged. Both strict JSON/default runs pass within180 seconds/180 MiB.',
'REVIEW':'See evidence/primary/ROOT_REVIEW.md, evidence/root/ROOT_PRIMARY_REVIEW.md and NATIVE_PRIMARY_REVIEW.md. These are mathematical frozen-proof reviews, not independent port review. PORT_EXECUTION_RECEIPT records port-author comparisons.',
'HANDOFF':'Integrate source and both scripts with a claim-local independent-helper mapping. No runtime dependencies: both scripts are self-contained. Preserve original raw/clarification chronology. Root canonical review precedes graph; immediately stage actual runner-cache stdout after cache execution.',
'QUEUE':'Root port review, isolated integration and required validation. No additional physics tuning requested.',
'OPPORTUNITY_QUEUE':'A native local compiler and deterministic preparation remain separate physical obligations. This finite storage theorem does not resolve them.',
'N1_N8':'N1 fixed cubic link metric. N2 supplied compact29 dynamics and time/couplings. N3 full PW blocks32 retain boundary flux. N4 finite local energy and explicit p. N5 five literal scope lines and29/28 unique named controls. N6 actual Wilson-loop singlet-loss adverse example and historical corrections. N7 analytical Haar/domain/all-orders premises are explicit. N8 no continuum, full-state/all-input or native compiler claim.'}
for n,t in items.items():(p/(n+'.md')).write_text('# '+n.replace('_',' ').title()+'\n\n'+t+'\n')
(p/'STATE.yaml').write_text('status: ready_for_root_port_review\nclaim_count: 1\nrepo_edits: false\ncanonical_cache_pending: true\nresource_seconds: 180\nresource_mib: 180\nprimary_checks: 29\nindependent_checks: 28\n')
(p/'PACK_INDEX.md').write_text('# Local observable finite-region/PW package\n\nCanonical source in docs preserves root897efdbc proof verbatim. scripts contains geometry primary and independent Wilson-Schmidt/tail helper. evidence/primary retains independent f062934 proof, all earlier versions and clarification records; evidence/root retains sharper proof, prospective contract and actual independent raw. NATIVE_PRIMARY_REVIEW.md and the copied root/primary reviews preserve cross-review scope. PORT_EXECUTION_RECEIPT.json binds source and runners to live JSON/default receipts and exact unchanged scientific payloads. Protocol files are retrospective staging indexes, not fabricated prospective evidence.\n\nNo repository integration or cache claim is made. Root port review remains pending.\n')
(p/'HASHES.json').write_text(json.dumps({str(f.relative_to(p)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(p.rglob('*')) if f.is_file() and f.name!='HASHES.json'},indent=2)+'\n')
print(hashlib.sha256((p/'PACK_INDEX.md').read_bytes()).hexdigest())
