import itertools,json,hashlib
from pathlib import Path
from fractions import Fraction as F
# Rotation group generated by quarter turns, not signed-permutation enumeration.
# indices +x,-x,+y,-y,+z,-z
rx=(0,1,4,5,3,2);rz=(2,3,1,0,4,5)
G={tuple(range(6))};todo=list(G)
while todo:
 a=todo.pop()
 for b in (rx,rz):
  c=tuple(b[a[i]] for i in range(6))
  if c not in G:G.add(c);todo.append(c)
assert len(G)==24
cs=list(itertools.product((-1,0,1),repeat=6));left=set(cs);sizes=[]
while left:
 c=left.pop(); orb={tuple(c[g[i]] for i in range(6)) for g in G};left-=orb;sizes.append(len(orb))
# Independently derived axis classes: identity, face quarter/half, vertex120, edgehalf.
classes=[(1,6),(6,3),(3,4),(8,2),(6,3)]
fixedsum=sum(n*3**cycles for n,cycles in classes)
assert fixedsum==1368 and fixedsum//24==len(sizes)==57
root=Path(__file__).resolve().parents[1]/'probability-family'
x=json.loads((root/'result.json').read_text())
assert x['cubic_orbit_count']==57 and x['assertions']==len(x['checks'])==27
hist={str(n):sizes.count(n) for n in set(sizes)}
assert hist==x['orbit_size_histogram']
for row,k in zip(x['law_rows'],(F(1,3),F(2,3))):
 expected=[F(1,2)+k*sum(c)/12 for c in cs]
 assert list(map(F,row['all_rows']))==expected
 assert F(row['min'])==(1-k)/2 and F(row['max'])==(1+k)/2
assert x['source_sha256']==hashlib.sha256((root/'check.py').read_bytes()).hexdigest()
print(json.dumps({'status':'PASS','independent_rotation_construction':'quarter-turn generators and closure','burnside_classes':classes,'fixed_sum':fixedsum,'orbit_count':len(sizes),'orbit_histogram':hist,'all_probability_rows_checked':1458,'exact_one_neighbor_difference':str(F(5,9)-F(19,36))},indent=2))
