import pathlib,json,hashlib
import numpy as np
p=pathlib.Path(__file__).resolve().parent;x=json.loads((p/'ANALYSIS.json').read_text());s=json.loads((p/'STATUS.json').read_text())
if len(s)!=96 or any(r['exit'] for r in s):raise RuntimeError('incomplete production')
lines=['# Local L4 finite-projector reptation results','', 'All96 frozen two-chain shards completed: six logical cells,32 independent chains each,64n measured attempted updates. Long-burn32n arms remain primary. No replacements or coverage changes. These are finite-projection path-chain research estimates, not a ground-state or convergence certificate.', '',f"Subprocess wall total {sum(r['seconds'] for r in s):.6f}s plus .0910385s measurement micro. Maximum shard wall {max(r['seconds'] for r in s):.6f}s; maximum reported RSS {max(json.loads((p/(r['name']+'.json')).read_text())['rss_mib'] for r in s):.6f}MiB.", '', '|tau|burn/n|harmonic|ratio|replica SE|precision|','|---|---|---|---|---|---|']
for c in x['cells']:
 for r in c['ratios']:lines.append(f"|{c['tau']}|{c['burn_multiplier']}|{r['harmonic']}|{r.get('ratio','invalid')}|{r.get('SE','invalid')}|{r.get('precision',False)}|")
ratios=[r for c in x['cells'] for r in c['ratios']];flags=[r for r in x['comparisons'] if r['flag']]
lines+=['',f"Nominal precision4SE<=10%ratio passes{sum(r.get('precision',False) for r in ratios)}/{len(ratios)}. Flagged comparisons{len(flags)}/{len(x['comparisons'])} at4SE; full comparisons remain in ANALYSIS.json. There is no exact L4 target consistency gate. Unflagged differences do not establish equilibration or negligible finite-projection bias.", '', 'Flagged comparisons: '+json.dumps(flags), '', 'The estimator uses midpointNf and both harmonic structure factors, with endpoint energy measured on the same chain. Their full chain-vector covariance, ratio influence vectors, chain influence covariance and estimator covariance(/32) are retained. The covariance diagonal is checked against SE². Every ordered16-batch vector and acceptance/self/rejection/direction-run counter is in the raw shard JSON. Strong overlap of adjacent midpoint paths is not treated as independent sampling;32 chains provide the replica units.', '', 'n=384tau is the TOTAL projector-bond count, with one-sided projectiontime n/(2M)=tau. The exact finite-G midpoint law is a squared projected trial amplitude. Its Dirichlet ratio is not automatically the ground spectral first moment. The initial paths were all seed/self and finite burn was supplied. No branching population is used, but this does not remove path equilibration, finite projection or finite-chain ratio errors.', '', 'Source and full local import closure remain frozen: production.py imports only own core.py; NumPy/standard Python are external software imports. No campaign module is read at production runtime. Original micro/core/freezes and review corrections remain preserved. No physical exponent, photon/pole, method equality or ground-state conclusion is inferred from these cells.', '', 'PRODUCTION_FINAL_HASHES.json binds every raw shard and source/report. No additional sampling was launched.']
(p/'PRODUCTION_REPORT.md').write_text('\n'.join(lines)+'\n')
files=['ANALYSIS.json','PRODUCTION_REPORT.md','PRODUCTION_FREEZE.json','core.py','production.py','analyze.py','launch.py','PRODUCTION_PROTOCOL.md','DEPENDENCIES.md','STATUS.json','STARTED.json','PRODUCTION.stdout','PRODUCTION.stderr']+[r['name']+e for r in s for e in ['.json','.stderr']]
(p/'PRODUCTION_FINAL_HASHES.json').write_text(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in files},indent=2)+'\n')
print(hashlib.sha256((p/'PRODUCTION_REPORT.md').read_bytes()).hexdigest())
