from pathlib import Path
import shutil
B=Path(__file__).resolve().parent;S=B.parent/'continuous-time-l2-calibration'
for n in ('runtime.py','conditional.py','bridge.py','geometry_reference.py','SUPPLEMENT.json','preflight.py','producer.py','analyze.py','launch.py','freeze.py'):
 shutil.copy2(S/n,B/n)
(B/'config.py').write_text("from pathlib import Path\nB=Path(__file__).resolve().parent\nARMS=[dict(arm=i,T=T,start=s,burn=64) for i,(T,s) in enumerate((T,s) for T in (.5,2.) for s in ('constant','bounded'))]\nCHAINS=64;MEASURED=256;FACES=24;BATCHES=16;SHARD=4\nSEED_BASE=202609360000\nMICRO_LEDGER=180.930914\ndef seed(a,c):return SEED_BASE+1000*a+c\n")
p=B/'producer.py';t=p.read_text().replace("a['burn']+128","a['burn']+config.MEASURED").replace('range(i,i+8))/8','range(i,i+16))/16').replace('range(0,128,8)','range(0,config.MEASURED,16)').replace('0<=a<8 or not 0<=s<4','0<=a<4 or not 0<=s<16');p.write_text(t)
p=B/'analyze.py';t=p.read_text().replace('len(rows)!=128','len(rows)!=config.MEASURED').replace('rows[i:i+8]','rows[i:i+16]').replace('range(0,128,8)','range(0,config.MEASURED,16)').replace("a['burn']+128","a['burn']+config.MEASURED").replace('24*128','24*config.MEASURED').replace('long=(1,3,5,7)','long=(0,1,2,3)').replace('# Every measured chain must cover all24 faces, including short arms.','# Every measured chain must cover all24 faces.').replace('([1,3],[5,7])','([0,1],[2,3])').replace('])!=32','])!=64').replace('for s in range(4):','for s in range(16):').replace('mean(x[:64]),mean(x[64:])','mean(x[:128]),mean(x[128:])').replace('[(1,3),(5,7),(0,1),(2,3),(4,5),(6,7)]','[(0,1),(2,3)]').replace('all_eight_arm_descriptive_gates','all_four_arm_descriptive_gates');p.write_text(t)
p=B/'launch.py';t=p.read_text().replace('jobs=32,chains=128','jobs=64,chains=256').replace('for a in range(8):','for a in range(4):').replace('for s in range(4):','for s in range(16):').replace('jobs=32,analysis_sha','jobs=64,analysis_sha');p.write_text(t)
p=B/'freeze.py';t=p.read_text().replace("import runtime,conditional,bridge,geometry_reference,config,preflight,producer,analyze,launch","import runtime,conditional,bridge,geometry_reference,config,preflight,producer,analyze,launch").replace("cost/'FINAL_FREEZE.json',","cost/'FINAL_FREEZE.json',B.parent/'continuous-time-l2-calibration/FINAL_FREEZE.json',").replace('refs[2:]','refs[3:]');p.write_text(t)
