from pathlib import Path
import json,hashlib,numpy as np
p=Path(__file__).resolve().parent;s=json.loads((p/'SUMMARY.json').read_text());status=json.loads((p/'STATUS.json').read_text())
lines=['# Fixed RK local-moment pilot: completed, with a cost-efficiency failure','',
'The preregistered four cells completed without resource or coverage reduction. All 32 chains in each cell and both burn protocols are retained. This is a finite RK component sampler and local-observable test, not a detuned calculation, stationary-measure certificate, full ground selection, isolated pole or photon claim. No L4 Hilbert-space enumeration occurred.','',
'## Source and pre-production review','',
'Pilot source SHA256 `'+hashlib.sha256((p/'pilot.py').read_bytes()).hexdigest()+'`; analysis SHA256 `'+hashlib.sha256((p/'analyze.py').read_bytes()).hexdigest()+'`. The fixed proposal and PREREGISTRATION precede production. Independent reviewer read the full observable/analysis, executed independently reconstructed L2/L4 controls, and closed the timing delta before launch; see sibling `ice-rk-pilot-cold-review/CODE_REVIEW.md` and `TIMING_DELTA.md`. The cost patch leaves trajectories unchanged and its previous source/diff are retained.','',
'Both micro receipts pass all 864 states and 41,472 signed-update cases. Their combined time was 4.491 seconds; revised micro RSS210.20MiB. Two actual adverse scripts (omit staggering, wrong orientation) fail mathematical assertions. An unavailable `python` alias exited127 before execution; its stderr is preserved, and `python3` performed the successful revised micro. These are distinct from scientific failures.','',
'## Resources and fixed sampling','',
'Four child runs totaled %.6f seconds (%.6f seconds including subprocess overhead), maximum production RSS %.3fMiB. Each was below120seconds/384MiB, far below the510second aggregate envelope. All128 chains and32768 per-chain measurements are retained in four NPZ files; the six/twelve simultaneously measured modes are correlated and are not additional independent replicas.'%(sum(r['seconds'] for r in s['rows']),sum(r['seconds'] for r in status),max(r['rss_mib'] for r in s['rows'])),'',
'Each sweep makes3L^3 uniform geometric plaquette proposals and flips if flippable. The observable channels are complex O, |O|², d=qhat²N_f^(ab)/(2L³), and |LO|² with signed complex changes summed before squaring. SEs below are independent-chain delta estimates retaining numerator/denominator covariance. The means are finite-chain estimates, not exact stationary values.','',
'## All mode estimates','',
'|L|burn|harmonic, momentum, polarization|S ± SE|mu1 ± SE|mu2 ± SE|','|---|---|---|---|---|---|']
for r in s['rows']:
 for m in r['modes']:
  lines.append('|%d|%d|%s|%.6f ± %.6f|%.6f ± %.6f|%.6f ± %.6f|'%(r['L'],r['burn'],str(m['mode']),m['S'],m['S_SE'],m['mu1']['ratio'],m['mu1']['chain_delta_SE'],m['mu2']['ratio'],m['mu2']['chain_delta_SE']))
lines += ['', 'All36 L2 checks (three quantities, six modes, two burns) satisfy the declared4SE+1e-8 comparisons with S=5/12, mu1=8/5, mu2=16/5. All54 burn comparisons and72 paired split-half moment comparisons have no declared4SE flag. These thresholds are diagnostic, not a proved simultaneous confidence level or mixing bound. The finite-window, within-chain-centered influence ESS ranges from %.1f to %.1f for mu1; it is not certified effective sample size. Full ACFs and block/chain comparisons remain in SUMMARY.json.'%(min(m['mu1']['within_chain_ac']['ESS'] for r in s['rows'] for m in r['modes']),max(m['mu1']['within_chain_ac']['ESS'] for r in s['rows'] for m in r['modes'])), '',
'L2 harmonic1 and L4 harmonic2 share q=π. For the fixed (momentum0,polarization1), burn128 comparison, mu1 changes from1.605585±0.033632 to1.409817±0.020770 and S from0.419678±0.008722 to0.376381±0.005520. Equality was not a pass requirement; this is a finite-volume change. L4 harmonic1 has q=π/2, with mu1 approximately0.70 and mu2 approximately0.90. It is a different momentum, not another matched-volume estimate. A centroid or Rayleigh upper bound does not identify a pole, gap equality or dispersion exponent.', '',
'## Actual measurement cost: unfavorable for conditioning here','',
'Cost is warmed wall time on2048 saved snapshots per cell,20 repetitions. One-face proposals use a separate RNG after production. Updating benchmarks copy snapshots and include amortized seeding/copying, so they are not an exact decomposition of production runtime. Times are empirical and lack a timing confidence interval. No count is assumed to be maintained for free.', '',
'|L|burn|update-only sweep μs|full measurement μs|one-face numerator μs|count numerator μs|count/one ratio-influence variance×cost range|','|---|---|---|---|---|---|---|']
for r in s['rows']:
 q=json.loads((p/f"L{r['L']}_b{r['burn']}.json").read_text());rat=[m['ratio_influence_variance_cost']['count_over_one'] for m in r['modes']]
 lines.append('|%d|%d|%.4f|%.4f|%.4f|%.4f|%.3f–%.3f|'%(r['L'],r['burn'],q['update_only_sweep_seconds_per_snapshot']*1e6,q['full_measurement_seconds_per_snapshot']*1e6,q['timing_seconds_per_snapshot']['1']*1e6,q['timing_seconds_per_snapshot']['2']*1e6,min(rat),max(rat)))
lines += ['', 'Every count/one ratio-influence variance×kernel-cost exceeds1: conditioning reduces snapshot variance but costs more than the reduction saves in this implementation. The all-face literal method is still slower. This is the preregistered computational-effectiveness failure, preserved without tuning. It is not an end-to-end MCMC asymptotic-variance comparison: update cost, cross-time covariance, shared measurement needs and incrementally maintained counts could change that comparison and were not silently credited.', '',
'## Remaining obligation','',
'The RK local sum-rule readout works at L4 with modest observed cost and percent-scale finite-chain uncertainty, avoiding a tiny late-time correlation signal. The stationary component assumption still lacks a quantitative mixing proof; the tests do not identify all zero-flux components. Exact detuned ground weighting is absent. Larger volumes, an optimized incremental estimator, stationary error guarantees, spectral concentration and photon inference require new work and scope. No additional job is launched by this report.']
(p/'REPORT.md').write_text('\n'.join(lines)+'\n')
files=[x for x in p.iterdir() if x.is_file() and x.name not in ['HASHES.json']]
(p/'HASHES.json').write_text(json.dumps({x.name:hashlib.sha256(x.read_bytes()).hexdigest() for x in sorted(files)},indent=2)+'\n')
