from pathlib import Path
import json,hashlib,datetime
p=Path(__file__).parent;x=json.loads((p/'ANALYSIS.json').read_text());status=json.loads((p/'STATUS.json').read_text());micro=json.loads((p/'FORECAST.json').read_text())['micro'];raw=[json.loads((p/(r['name']+'.json')).read_text()) for r in status]
wall=sum(r['seconds'] for r in status);rss=max(r['rss_mib'] for r in raw)
lines=['# Propagated L4 fixed-study result','',f'All 32 fixed shards completed successfully: four arms, 16 independent chains per arm, 32n measured updates per chain. Production wall time {wall:.6f} s; charged total including the original micro {wall+micro:.6f} s. Maximum shard {max(r["seconds"] for r in status):.6f} s; maximum reported RSS {rss:.6f} MiB. No replacements, additional arms, or source changes during production.','',f'Frozen analyzer status: `{x["status"]}`. All 8 nominal D precision gates pass; 0 of 18 predeclared comparison flags. These are finite-chain diagnostics, not evidence establishing stationarity, ground-state convergence, or an excitation pole.','', '| Arm (tau,RK sweeps,burn/n) | h | D ± chain SE | R ± chain SE | correction ± SE | signed VarH ± SE |','|---|---:|---|---|---|---|']
for a in x['arms']:
 for r in a['rows']:
  lines.append(f'| {a["parameters"]} | {r["harmonic"]} | {r["D"]:.9g} ± {r["D_SE"]:.4g} | {r["R"]:.9g} ± {r["R_SE"]:.4g} | {r["correction"]:.6g} ± {r["correction_SE"]:.4g} | {r["VarH"]:.6g} ± {r["VarH_SE"]:.4g} |')
lines+=['','All 8 residual-resolution and variance-resolution classifications are indeterminate. Arm D has negative signed VarH, retained without clipping; its bound plugin is null. Positive plug-in variance values in other arms are also unresolved and do not provide certified bounds.','', 'Original-tag fractions are zero in arms A, B and D. Arm C ranges from zero to '+str(max(x['arms'][2]['tag_fractions']))+'; every chain remains below the predeclared 1% flag. This checks survival of the original path labels, not forgetting of all initialization effects.','', 'R and Epsi identities refer to the stationary product-G path measure. The propagated initializer samples a finite RK start followed by product Q, not that equilibrium path law. Until stationarity is established, the measured ratios and cross moments are diagnostics rather than exact Rayleigh quotients of an inferred state. Lack of flagged differences is not convergence; no L4 exact oracle exists here.','', 'The original failed constant-path L4 study remains untouched. This prospectively specified propagated-start study reduces the observed original-tag retention and avoids the previous large disagreements, but does not prove a causal decomposition of all earlier bias.','', 'Full chain vectors, 16 within-chain batches, acceptance counters, accepted-run histories, initial-tag replay data, signed moments, chain influences and estimator covariance are retained in raw shard JSON and ANALYSIS.json. Batches were not treated as independent replicas.','', 'Provenance: freeze d666579d4f33c95a8a1835852c54e7bf28b7f8eadd285c9629034bba8bba4c66; independent review fe1f7bb43066e430fe88804734cb2ec4693f83d4035e111ebd21157cb6580689. Earlier freezes, the integrity-repair evidence and exact cost-micro producer are preserved.']
(p/'PRODUCTION_REPORT.md').write_text('\n'.join(lines)+'\n')
(p/'COMPLETED.json').write_text(json.dumps(dict(utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),shards=len(status),production_seconds=wall,micro_seconds=micro,charged_seconds=wall+micro,max_rss_mib=rss,status=x['status'],production_extension=False),indent=2)+'\n')
files=['ANALYSIS.json','PRODUCTION_REPORT.md','COMPLETED.json','STARTED.json','STATUS.json','LAUNCH.stdout','LAUNCH.stderr']+[r['name']+suffix for r in status for suffix in ['.json','.stderr']]
(p/'FINAL_RESULTS_HASHES.json').write_text(json.dumps({f:hashlib.sha256((p/f).read_bytes()).hexdigest() for f in files},indent=2)+'\n')
print((p/'COMPLETED.json').read_text());print('report',hashlib.sha256((p/'PRODUCTION_REPORT.md').read_bytes()).hexdigest())
