from pathlib import Path
import json,hashlib,subprocess,sys,shutil
W=Path('/private/tmp/toe-native-charged-record-histories-20260909');P=W/'.claude/science/physics-loops/native-charged-record-histories-20260909';R=P/'PORT_RECORDS';R.mkdir(exist_ok=True)
common='Current surface: conditional-support; finite supplied native carrier and Born/Lueders instrument. No occurrence, nearest-neighbor law, role selection or effective audit grade is supplied.\n'
rows={'GOAL.md':'Construct exact full-carrier gauge-corrected Record histories and retain the physical-law supplier gap.','ASSUMPTIONS_AND_IMPORTS.md':'Two load-bearing parents: actual8038 full native dictionary and native edge instrument. Graph/order/ordinary tensor composition and the quantum instrument remain supplied. No extra physical qubit is added.','ROUTE_PORTFOLIO.md':'Charged-sector contraction is the primary frame. All-positive correction has local Z dressing and projective history composition. Scalar menu and isolated occupation-detector routes add no current supplier closure.','OPPORTUNITY_QUEUE.md':'Next target: an actual native formation/dwell family with nearest-neighbor conditional probabilities, without reassigning a controller as an axiom.','NO_GO_LEDGER.md':'False refinement equality was caught before review: forgotten finer outcomes dephase or discard rather than undo formation. Preserve predecessor. Generic full-carrier nonbridge outcomes need not be fair.','LITERATURE_BRIDGES.md':'Read latestmain0c52 plus open8038/8037 and7326/6347. No historical priority claim. Full source path/pin register in ORIGINAL.','ARTIFACT_PLAN.md':'One note, primary and two helpers, paired output, six-file isolated closure, source mutations and exact proof history. No graph/commit/PR by author.','TRACE_GATE.md':'trace_class: frontier_discovery\nreachability_to_target: supports\nhypothetical_axiom_status: null\nadmitted_observation_status: null\nproposal_allowed: false\nbare_retained_allowed: false\naudit_required_before_effective_retained: true','CLAIM_STATUS_CERTIFICATE.md':'actual_current_surface_status: conditional-support\nconditional_surface_status: finite instrument/dictionary theorem\nThe finite controls do not prove physical formation or Born selection.','REVIEW_HISTORY.md':'Root read scratch7728 proof before port; independent canonical review pending. Author implemented original and port, so this is not an independent replication. Small controls and actual mutations support implementation only.','HANDOFF.md':'Source frozen for root and independent source review. Root owns isolated integration acceptance and graph serialization; no commit/push until reviewed.','PR_BACKLOG.md':'Stack on dictionary8038 exact86e03ef9, notlatestmain. No PR opened. Parent must land or be integrated beforemain.'}
for n,text in rows.items():(P/n).write_text('# '+n[:-3].replace('_',' ')+'\n\n'+common+'\n'+text+'\n')
(P/'STATE.yaml').write_text('status: source_frozen_for_review\nbranch: codex/native-charged-record-histories-20260909\nbase: 86e03ef9a8eaafb9106304bf54cc0a991c758001\nactual_current_surface_status: conditional-support\nnext: independent_source_review\n')
names=['docs/NATIVE_CHARGED_RECORD_HISTORIES_NOTE_2026-09-09.md','docs/NATIVE_DYNAMICAL_CYCLE_FERMION_Z2_DICTIONARY_NOTE_2026-09-08.md','docs/NATIVE_EDGE_RECORD_MATTER_INSTRUMENT_AND_ENERGY_LEDGER_BOUNDED_THEOREM_NOTE_2026-09-05.md','scripts/native_charged_record_histories_2026_09_09.py','scripts/native_charged_record_history_controls_2026_09_09.py','scripts/native_charged_record_history_car_2026_09_09.py'];m={n:hashlib.sha256((W/n).read_bytes()).hexdigest() for n in names};(R/'SOURCE_FREEZE.json').write_text(json.dumps(m,indent=2)+'\n');isolated=R/'isolated';isolated.mkdir(exist_ok=True)
for n in names:p=isolated/n;p.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(W/n,p)
cmd=[sys.executable,'-I','-B','-S','-OO',str(isolated/names[3]),'--json'];r=subprocess.run(cmd,capture_output=True,text=True,timeout=30);(R/'ISOLATED.stdout').write_text(r.stdout);(R/'ISOLATED.stderr').write_text(r.stderr)
if r.returncode:raise RuntimeError(r.stderr)
actual=json.loads(r.stdout);old=json.loads((W/'outputs/native_charged_record_histories_2026_09_09.json').read_text())
# Timings and source-path-independent hashes may differ only in timings.
for z in [actual,old]:
 z.pop('seconds');z.pop('peak_rss_bytes')
 for q in z['controls']:q.pop('seconds',None)
if actual!=old:raise ValueError('isolated payload')
mutants=[]
for label,name,a,b in [('omit_dressing',names[4],'if a and not wrong else 1','if False else 1'),('commute_adjacent',names[4],'sign=(-1)**(a*b*bool(set(e)&set(f)))','sign=1'),('bare_number',names[5],'(1-((shifted>>k)&1)) if k in (i,j) else ((shifted>>k)&1)','((shifted>>k)&1)')]:
 s=(W/name).read_text()
 if a not in s:raise ValueError('mutation target')
 s=s.replace(a,b);p=R/(label+'.py');p.write_text(s+"\nif __name__=='__main__':check()\n");z=subprocess.run([sys.executable,'-I','-B','-S','-OO',str(p)],capture_output=True,text=True,timeout=30);(R/(label+'.stderr')).write_text(z.stderr)
 if z.returncode==0:raise ValueError('survived mutant')
 mutants.append(dict(name=label,returncode=z.returncode,sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
(R/'CONTROL_RECEIPT.json').write_text(json.dumps(dict(status='PASS',isolated_files=6,payload_equal=True,mutants=mutants,physical_runs=0),indent=2)+'\n');print('freeze',hashlib.sha256((R/'SOURCE_FREEZE.json').read_bytes()).hexdigest());print('note',m[names[0]])
