import pathlib,json,hashlib
import numpy as np
p=pathlib.Path(__file__).resolve().parent;x=json.loads((p/'ANALYSIS.json').read_text());status=json.loads((p/'STATUS.json').read_text());require=lambda c: None if c else (_ for _ in ()).throw(RuntimeError('coverage'));require(len(status)==9 and all(r['exit']==0 for r in status))
lines=['# Exact-graph L2 reptation production','', 'All nine frozen cells completed,32 independent chains each,65536 measured attempted updates. Warm32n remains primary; oracle-assisted stationary-start is an L2-only diagnostic. No replacements, seed changes or extra production.','',f"Subprocess wall total {sum(r['seconds'] for r in status):.6f}s; plus frozen micro {json.loads((p/'MICRO.json').read_text())['seconds']:.6f}s. Maximum cell wall {max(r['seconds'] for r in status):.6f}s. Maximum RSS {max(json.loads((p/f'cell{i}.json').read_text())['rss_mib'] for i in range(9)):.6f}MiB.",'','|n|burn multiplier|finite ratio|replica SE|finite-G target|consistency|precision|','|---|---|---|---|---|---|---|']
diags=[]
for row in x['cells']:
 lines.append(f"|{row['n']}|{row['burn_multiplier']}|{row['ratio']:.9f}|{row['SE']:.9f}|{row['target']:.9f}|{row['consistency']}|{row['precision']}|")
 raw=json.loads((p/f"cell{row['cell']}.json").read_text());cs=raw['counters'];bm=np.array(raw['batch_means']);z=bm-bm.mean(1,keepdims=True);den=np.mean(z*z,axis=(0,1));lag=np.mean(z[:,:-1]*z[:,1:],axis=(0,1))/den
 diags.append(dict(cell=row['cell'],self_proposals=sum(c['self_proposals'] for c in cs),accepted_self=sum(c['accepted_self'] for c in cs),rejections=sum(c['rejections'] for c in cs),accepted=sum(c['accepted'] for c in cs),window_traversals_including_burn=sum(c['window_traversals'] for c in cs),batch_lag1_descriptive=lag.tolist()))
lines += ['', 'All9 ratio comparisons pass the frozen4SE finite-target criterion and all9 pass4SE<=10%target precision. All9 independent arm comparisons are unflagged. This does not prove warm-start convergence, validate arbitrary larger-volume mixing, or make the finite-projector ratio a ground excitation. The exact-start arm removes initialization error in the ideal finite path law but uses finite-precision CDF sampling and an L2 oracle unavailable in a scalable general implementation.', '', 'Finite-G targets correspond to total path bonds n and one-sided tau=n/48. Increasing n changes the exact target and observed uncertainty. The n48 target1.660993330 differs from the n768 target1.664333052; no continuous-time substitution or ground-limit identity is silently made. Primary estimates are n48:1.661448212±.002773677; n192:1.669033958±.003327607; n768:1.661345825±.005966195 (one replica SE).', '', 'Full chain vectors/covariance and ratio influences are in ANALYSIS.json; every ordered16-batch vector and self/accept/reject/direction-run counter is in cell raw JSON. Batches and individual updates are not independent replicas. DIAGNOSTICS.json adds descriptive lag-one correlation of demeaned ordered batch vectors, not an integrated autocorrelation time or energy ESS. Window traversals count complete runs of accepted shifts, including burn; they are not independent samples or physical round trips.', '', 'No all-time raw configuration history was promised or retained in production: the raw objects are all frozen chain vectors, batch vectors and event diagnostics. The micro retains its own step-level series and reconstruction evidence. All permanent preproduction and original six-cell freezes remain unchanged.', '', 'This removes branching population bias for the correctly sampled finite path model, not finite projection or path-chain sampling errors. No L4 production/port is authorized by these results. PRODUCTION_FINAL_HASHES.json binds all source, raw, analysis and reports.']
(p/'DIAGNOSTICS.json').write_text(json.dumps(diags,indent=2)+'\n');(p/'PRODUCTION_REPORT.md').write_text('\n'.join(lines)+'\n')
files=['PRODUCTION_REPORT.md','DIAGNOSTICS.json','ANALYSIS.json','STATUS.json','STARTED.json','PRODUCTION_FREEZE.json','production.py','graph.py','initializer.py','analyze.py','launch.py','PRODUCTION_PROTOCOL.md','PRODUCTION.stdout','PRODUCTION.stderr']+[f'cell{i}{suffix}' for i in range(9) for suffix in ['.json','.stderr']]
(p/'PRODUCTION_FINAL_HASHES.json').write_text(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in files},indent=2)+'\n')
print(sum(r['seconds'] for r in status));print(hashlib.sha256((p/'PRODUCTION_REPORT.md').read_bytes()).hexdigest())
