import json,hashlib,pathlib
p=pathlib.Path(__file__).resolve().parent
x=json.loads((p/'ANALYSIS.json').read_text());status=json.loads((p/'STATUS.json').read_text());micro=json.loads((p/'MICRO.json').read_text())
lines=['# Frozen RK regulated inverse-moment pilot results','', 'All four authorized cells completed without replacements: L2/L4, burns32/128,32 independent chain units and256 origins each. Each first origin is burn+1 sweeps; lag namespace is400000000+chain_id. Kernel and schedule were unchanged after independent preproduction review.','',f"Subprocess wall total {sum(r['seconds'] for r in status):.9f}s; including micro {sum(r['seconds'] for r in status)+micro['seconds']:.9f}s. Maximum cell RSS {max(json.loads((p/(r['cell']+'.json')).read_text())['rss_mib'] for r in status):.6f}MiB. These are actual end-to-end cell timings, substantially below the deliberately conservative forecast; they do not establish comparative asymptotic efficiency.",'','| L | burn | harmonic | alpha | truncated r | replica SE | exact consistency | precision |','|---|---|---|---|---|---|---|---|']
for c in x['rows']:
 for r in c['rows']:
  lines.append(f"|{c['L']}|{c['burn']}|{r['harmonic']}|{r['alpha']}|{r['r_truncated']:.9f}|{r['SE']:.9f}|{r.get('consistency_nominal','no L4 oracle')}|{r['precision_nominal']}|")
lines += ['', 'All6 L2 exact truncated-target comparisons satisfy the predeclared4SE criterion. Precision4SE<=10%r passes14/18 rows: alpha.25 fails at both L2 burns and both L4 harmonic2 burns. Thus the full precision criterion fails; no extra chains or altered regulators were run. All9 independent-burn comparisons are unflagged at4SE; absence of a flag is not a mixing or stationarity certificate. All pooled numerators/denominators are positive, and no chain-level real numerator mean is negative; signed complex products and imaginary diagnostics remain in raw output.', '', 'The estimate is the geometric elementary-step resolvent with discarded K>Kmax contributions set to zero, not replacement by a capped endpoint. Kmax L2=[800,368,169], L4=[6373,2922,1329]. For each alpha the stationary clipping error is bounded analytically by q^(Kmax+1)/alpha<=.001; floating values are reported alongside exact rational comparisons. Clipped counts by cell: '+str([(c['L'],c['burn'],c['clipped_counts']) for c in x['rows']])+'. The tail bound is distinct from replica sampling uncertainty and possible finite-burn bias.', '', 'The regulator remains finite: r_alpha integrates1/(omega+alpha), not1/omega. L2 comparisons use the exact truncated finite-component targets. L4 has no exact oracle here. Neither clipping control nor nominal confidence establishes the unregulated inverse moment. The reported1/r-alpha values are plug-in statistics, not rigorous gap bounds. The exact positive inelastic-measure inequality applies only to exact expectations on the declared component, not automatically to these estimates; no pole or photon inference is made.', '', 'ANALYSIS.json preserves all chain-level joint S/Y means, sample covariance across harmonics and alphas, ratio-influence covariance, paired-alpha differences and independent-burn comparisons. NPZ files preserve every complex origin, product, geometric lag and clipping flag. Four cells contain32768 origins total; origins and modes are not counted as independent replicas. No Nf was added after the freeze.', '', 'Frozen source checks and independent review are preproduction evidence, not additional stochastic replicas. Original micro source/hash and reporting repairs remain preserved. PRODUCTION_FINAL_HASHES.json binds this report, analysis, source and raw files.']
(p/'PRODUCTION_REPORT.md').write_text('\n'.join(lines)+'\n')
names=['kernel.py','run.py','analyze.py','launch.py','PREREGISTRATION.md','PREPRODUCTION_HASHES.json','STATUS.json','ANALYSIS.json','PRODUCTION_REPORT.md','PRODUCTION.stdout','PRODUCTION.stderr']
for r in status:names += [r['cell']+s for s in ['.json','.npz','.stderr']]
(p/'PRODUCTION_FINAL_HASHES.json').write_text(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in names},indent=2)+'\n')
print('report',hashlib.sha256((p/'PRODUCTION_REPORT.md').read_bytes()).hexdigest());print('analysis',hashlib.sha256((p/'ANALYSIS.json').read_bytes()).hexdigest())
