from pathlib import Path
import hashlib,json
p=Path(__file__).resolve().parent
texts={
'GOAL.md':'Stage two separate bounded results for the supplied finite compact cube: finite Peter-Weyl approximation and certified Galerkin eigenvalue enclosures. No repository integration is performed here.',
'ASSUMPTIONS_AND_IMPORTS.md':'Both notes import block29 full compact Hamiltonian H=K+V, a>0, v>=0, twelve SU(3) links, actual six plaquette potential and physical vertex Gauss subspace. Peter-Weyl, spectral/minmax theory and form-domain calculus are standard supplied mathematics. No finite carrier or coupling is derived from native axioms. Block33 imports block32 cutoff and threshold; numerical enclosure applications require genuinely certified Ritz intervals, not floating eigensolver values.',
'ROUTE_PORTFOLIO.md':'Block32 uses complete link representation blocks and projected Duhamel. Block33 uses strict Schur inertia and monotone endpoint inversion. They are distinct theorem claims in one coherent cutoff package. Whole-space energy-uniform approximation and an unqualified Ritz-gap lower bound are excluded.',
'NO_GO_LEDGER.md':'Preserved adverse cases: asymmetric omitted-shell choice overestimates threshold; finite-energy input can have zero cutoff projection; interacting cutoff does not commute with H; Ritz gap can err in either direction; an above-threshold omitted eigenvalue interleaves; rank-one actual R0 cannot certify a gap. See frozen checks and evidence/galerkin-spectrum/FAILURES.md. These are scoped failures, not universal impossibility claims.',
'LITERATURE_BRIDGES.md':'The proofs apply standard Peter-Weyl decomposition, Rayleigh-Ritz/minmax, Schur complements and form-core approximation to the supplied cube. No novelty is claimed for these general methods. Canonical parent29 supplies the compact Hamiltonian premise. No external numerical library output is treated as a certified enclosure.',
'ARTIFACT_PLAN.md':'Retrospective port index: docs contains two canonical notes; scripts contains two standalone exact certificates. evidence preserves original prospective contracts, proofs, raw results and failures. PORT_RECEIPT and EXECUTION_RECEIPT bind exact copies and live canonical runs. Canonical repository cache execution remains an integration task; scratch stdout is not misrepresented as a staged repository cache.',
'CLAIM_STATUS_CERTIFICATE.md':'Both sources explicitly carry Type bounded_theorem and conditional-support status. They provide finite-volume support under block29 supplied Hamiltonian. Neither supplies native admissibility, four-qubit compilation, a thermodynamic gap, or whole-spectrum uniform convergence.',
'REVIEW_HISTORY.md':'Block32 frozen proof f3a2a22c reviewed independently by primary and root. Block33 frozen proof d561d424 reviewed independently by primary and root. All four hash-specific reviews are copied at package root. Primary performed this port and does not declare an independent review of its own port. Root canonical review remains pending.',
'PR_BACKLOG.md':'Pending: root canonical port review, isolated worktree integration after block29 parent, actual canonical caches staged, graph/manifest/pipeline/strict/readiness and publication. No commit or PR was made from this scratch staging.',
'TRACE_GATE.md':'Mathematical source32 -> full block29 Hamiltonian; source33 -> source32 finite cutoff -> block29. Exact small-matrix checks support Schur formulas and adverse controls; they do not compute the cube spectrum. Actual Haar R0 coefficient is stated separately with its rank-one scope.',
'STATUS.md':'READY FOR ROOT PORT REVIEW. Proof bodies preserved verbatim. Scientific JSON fields and named science checks match original receipts exactly; cutoff adds one resource check. Live JSON and default stdout both pass within 180 seconds/180 MiB.',
'REVIEW.md':'See ROOT_CUTOFF_REVIEW.md, PRIMARY_CUTOFF_REVIEW.md, ROOT_GALERKIN_REVIEW.md and PRIMARY_GALERKIN_REVIEW.md. These review frozen mathematical inputs. Port comparison and execution receipts are validation by the port author, not independent port review.',
'HANDOFF.md':'Integrate only docs/scripts and coherent evidence protocol into an isolated worktree with block29 available. Preserve full proof/raw chronology. Run actual execute_and_write_cache and immediately stage .txt caches before generated cleanup. No runtime file dependencies are declared because these two runners are self-contained.',
'QUEUE.md':'1. Root canonical review. 2. Isolated integration and actual cache. 3. Required pipeline and scoped draft review publication. No extra physics optimization is queued.',
'OPPORTUNITY_QUEUE.md':'Future finite-carrier numerical spectral intervals would require a separate preregistered computation and certified interval arithmetic. Current exact fixtures are not actual large-cube spectra.',
'N1_N8.md':'N1: fixed twelve-link compact cube. N2: supplied a,v and block29 Hamiltonian. N3: complete Peter-Weyl blocks and exact Gauss action. N4: finite-form-energy inputs with explicit normalization/success conditions. N5: literal per_element/per_site/per_mode/per_block/lattice_wide stdout, with actual32 and43 named controls. N6: preserved adverse fixtures and original failed Boolean-count run. N7: certified intervals required; no floating spectral certification. N8: no thermodynamic, QCD, four-qubit compiler, or energy-uniform full-space claim.',
}
for name,text in texts.items(): (p/name).write_text('# '+name.removesuffix('.md').replace('_',' ').title()+'\n\n'+text+'\n')
(p/'STATE.yaml').write_text('status: ready_for_root_port_review\nrepo_edits: false\nclaim_count: 2\nproof_bodies_verbatim: true\ncanonical_cache_pending_integration: true\nresource_seconds: 180\nresource_mib: 180\n')
(p/'PACK_INDEX.md').write_text('# Compact cutoff and spectral enclosure package\n\nTwo separately scoped bounded-theorem sources depend on the full compact Hamiltonian parent29.\n\n- `docs/`: canonical finite-cutoff and Galerkin enclosure notes.\n- `scripts/`: standalone canonical exact runners, totals32 and43.\n- `evidence/`: immutable original proof, preregistration, raw and failures.\n- Four `*_REVIEW.md` files: independent frozen-proof reviews.\n- `PORT_RECEIPT.json`: exact hashes and unchanged proof bodies.\n- `EXECUTION_RECEIPT.json`: unchanged scientific payload comparison and live default runs.\n- `CUTOFF_RAW.json`, `GALERKIN_RAW.json`, and corresponding stdout: actual canonical receipts.\n- Protocol markdown and STATE.yaml: retrospective integration handoff, not fabricated prospective evidence.\n\nRoot canonical review and repository caches remain pending; no repository edits or publication occurred.\n')
h={str(f.relative_to(p)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(p.rglob('*')) if f.is_file() and f.name!='HASHES.json'}
(p/'HASHES.json').write_text(json.dumps(h,indent=2)+'\n')
print(json.dumps({k:v for k,v in h.items() if k.startswith(('docs/','scripts/')) or k=='PACK_INDEX.md'},indent=2))
