from pathlib import Path
import json,hashlib,shutil,ast
st=Path('/private/tmp/toe-autonomous-primary-20260907/compact-cutoff-staging');(st/'docs').mkdir(exist_ok=True);(st/'scripts').mkdir(exist_ok=True)
parent='GAUGE_WILSON_FULL_CUBE_COMPACT_INTERACTING_HAMILTONIAN_LIMIT_BOUNDED_THEOREM_NOTE_2026-09-07.md';parentid='gauge_wilson_full_cube_compact_interacting_hamiltonian_limit_bounded_theorem_note_2026-09-07'
entries=[('/private/tmp/toe-autonomous-orbital-20260907/finite-qubit-cutoff','gauge_wilson_compact_cube_finite_qubit_cutoff','GAUGE_WILSON_COMPACT_CUBE_FINITE_QUBIT_CUTOFF'),('/private/tmp/toe-autonomous-native-ladder-20260907/galerkin-spectrum','gauge_wilson_compact_cube_galerkin_spectral_enclosures','GAUGE_WILSON_COMPACT_CUBE_GALERKIN_SPECTRAL_ENCLOSURES')]
receipts={}
for index,(directory,stem,title) in enumerate(entries):
 p=Path(directory);shutil.copytree(p,st/'evidence'/p.name,ignore=shutil.ignore_patterns('__pycache__','staging'),dirs_exist_ok=True)
 old=(p/'check.py').read_text();t=old
 if index==0:
  t=t.replace('import os,time','import os,time,signal,sys\nAUDIT_TIMEOUT_SEC=180\nAUDIT_MEMORY_LIMIT_MB=180')
  t=t.replace('START=time.monotonic()','START=time.monotonic();signal.alarm(AUDIT_TIMEOUT_SEC)\nif sys.argv[1:] not in ([], [\'--json\']):raise SystemExit(\'usage: \'+sys.argv[0]+\' [--json]\')')
  t=t.replace('assert 0<rss<180 and time.monotonic()-START<180',"ck('positive resource budget',0<rss<180 and time.monotonic()-START<180)")
  t=t.replace('print(json.dumps(dict(status=', 'out=dict(status=',1).replace("source_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest()),indent=2))","source_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest())")
  t+="\nif sys.argv[1:]==['--json']:print(json.dumps(out,indent=2,allow_nan=False))\nelse:\n print('PASS finite carrier and energy-cutoff checks; TOTAL='+str(out['total'])+' (31 scientific +1 resource)')\n"
  scopes=['per_element: Exact Peter-Weyl shell sum and dimension polynomial.','per_site: Full8-vertex Gauss action preserved analytically; no lattice-state simulation.','per_mode: Five fixed cutoffs R=0,1,2,4,10 with exact link dimensions and12-link storage.','per_block: Balanced omitted thresholds and actual-Haar R0 leakage coefficient1/3.','lattice_wide: Fixed finite cube; four-link support on retained carrier, not four-qubit compiled controls.']
  for line in scopes:t+=' print('+repr(line)+')\n'
  t+=" print('cutoff_rows='+json.dumps(out['rows'],sort_keys=True))\n print('resources: elapsed_sec='+str(out['elapsed_seconds'])+' rss_MiB='+str(out['peak_rss_mib'])+'; limits=180sec/180MiB')\n print('source_sha256='+out['source_sha256'])\n"
 else:
  t=t.replace('import os,time,resource,json,hashlib,itertools','import os,time,resource,json,hashlib,itertools,signal,sys\nAUDIT_TIMEOUT_SEC=180\nAUDIT_MEMORY_LIMIT_MB=180')
  t=t.replace('started=time.monotonic()','started=time.monotonic();signal.alarm(AUDIT_TIMEOUT_SEC)\nif sys.argv[1:] not in ([], [\'--json\']):raise SystemExit(\'usage: \'+sys.argv[0]+\' [--json]\')')
  t=t.replace("os.environ['OMP_NUM_THREADS']='1'","os.environ['OMP_NUM_THREADS']='1';os.environ['MKL_NUM_THREADS']='1'")
  t=t.replace('resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/(1024*1024)',"resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/(1024*1024 if sys.platform=='darwin' else 1024)")
  t=t.replace('print(json.dumps(encode(result),indent=2,allow_nan=False))',"if sys.argv[1:]==['--json']:print(json.dumps(encode(result),indent=2,allow_nan=False))\nelse:\n print('PASS exact Schur/Ritz interval controls; TOTAL='+str(result['TOTAL']))")
  scopes=['per_element: Exact rational matrices, principal-minor positivity and Sturm root enclosures.','per_site: No whole-cube eigenvalue calculation; operator theorem uses full physical or link space.','per_mode: Four coupled2/3-dimensional fixtures plus one uncoupled interleaving adverse case.','per_block: Both directions of finite-gap error; actual-Haar R0 ground-only coupling imported explicitly.','lattice_wide: Fixed compact cube cutoff theorem; no full-spectrum uniform rate or thermodynamic claim.']
  for line in scopes:t+='\n print('+repr(line)+')'
  t+="\n print('actual_R0='+json.dumps(result['actual_R0'],sort_keys=True))\n for name,row in result['fixtures'].items():\n  if 'certified_gap_interval' in row:print(name+' certified_gap_interval='+json.dumps(encode(row['certified_gap_interval'])))\n print('resources: elapsed_sec='+str(result['seconds'])+' rss_MiB='+str(result['rss_MiB'])+'; limits=180sec/180MiB')\n print('source_sha256='+result['source_sha256'])\n"
 t='#!/usr/bin/env python3\n"""Finite compact cube cutoff/spectral support; exact scope in linked theorem."""\n'+t;ast.parse(t);rf=st/'scripts'/(stem+'_2026_09_07.py');rf.write_text(t)
 deps=[parentid]
 if index:deps.append('gauge_wilson_compact_cube_finite_qubit_cutoff_bounded_theorem_note_2026-09-07')
 scope='Finite Peter-Weyl carrier with exact Gauss action and finite-form-energy real-time projected Duhamel error, with explicit local dimension and normalized-input qualifications.' if not index else 'Low-energy exact spectral and first-gap enclosures for the actual compact cube Peter-Weyl cutoff, including strict Schur inertia and interval-certified Ritz values; no actual whole-cube numerical eigenvalues claimed.'
 head='---\nclaim_id: '+stem+'_bounded_theorem_note_2026-09-07\nclaim_type: bounded_theorem\nrunner: scripts/'+rf.name+'\nupstream_dependencies:\n'+''.join('  - '+x+'\n' for x in deps)+'claim_scope: '+json.dumps(scope)+'\n---\n\n**Type:** bounded_theorem\n\n```yaml\nactual_current_surface_status: conditional-support\nconditional_surface_status: conditional-support\ntrace_class: upstream_support\nreachability_to_target: supports\naudit_required_before_effective_retained: true\nbare_retained_allowed: false\nhypothetical_axiom_status: null\nadmitted_observation_status: null\n```\n\n'
 head+='The [full compact Hamiltonian parent]('+parent+') fixes the supplied full link/physical Gauss model. '
 if index:head+='The [finite cutoff parent](GAUGE_WILSON_COMPACT_CUBE_FINITE_QUBIT_CUTOFF_BOUNDED_THEOREM_NOTE_2026-09-07.md) fixes P_R, the exact local storage dimension, omitted kinetic threshold and actual Haar R0 coupling. '
 head+='The [exact runner](../scripts/'+rf.name+') records '+('31 scientific checks plus one resource control (TOTAL32)' if not index else '43 named finite checks including its resource guard')+'. Its finite controls do not replace the analytical form-domain proofs below.\n\n'
 if not index:head+='**Padding/support clarification.** Four-register support below is on the finite tensor carrier, with each register potentially containing several qubits. It is not a four-qubit interaction claim. A globally inert extension on the entire unused product-code complement can require all-code projectors and need not preserve four-register support on arbitrary ambient states. The source asserts no native local compiler or locality of that globally inert extension.\n\n'
 df=st/'docs'/(title+'_BOUNDED_THEOREM_NOTE_2026-09-07.md');df.write_text(head+(p/'DERIVATION.md').read_text());receipts[stem]=dict(original_proof_sha256=hashlib.sha256((p/'DERIVATION.md').read_bytes()).hexdigest(),canonical_source_sha256=hashlib.sha256(df.read_bytes()).hexdigest(),proof_body_verbatim=True,original_runner_sha256=hashlib.sha256((p/'check.py').read_bytes()).hexdigest(),canonical_runner_sha256=hashlib.sha256(rf.read_bytes()).hexdigest(),changes='Metadata, parent links, strict JSON/default scope interface, alarm before Sympy and portable resources;32adds explicit counted resource guard,33keeps43 namedchecks; no fixture/formula change.')
for name,file in [('ROOT_CUTOFF_REVIEW.md','/private/tmp/toe-campaign-20260907/finite-qubit-cutoff/ROOT_COLD_REVIEW.md'),('PRIMARY_CUTOFF_REVIEW.md','/private/tmp/toe-autonomous-primary-20260907/finite-qubit-cutoff-review/REVIEW.md'),('ROOT_GALERKIN_REVIEW.md','/private/tmp/toe-campaign-20260907/galerkin-spectrum/ROOT_COLD_REVIEW.md'),('PRIMARY_GALERKIN_REVIEW.md','/private/tmp/toe-autonomous-primary-20260907/galerkin-spectrum-review/REVIEW.md')]:shutil.copy2(file,st/name)
(st/'PORT_RECEIPT.json').write_text(json.dumps(receipts,indent=2)+'\n');print(st)
