import json,pathlib,hashlib
p=pathlib.Path(__file__).resolve().parent;x=json.loads((p/'ANALYSIS.json').read_text());status=json.loads((p/'STATUS.json').read_text());forecast=json.loads((p/'FORECAST_PRODUCTION.json').read_text())
assert len(status)==24 and all(r['exit']==0 for r in status)
lines=['# Frozen RK size-ladder results','', 'All24 fixed shards completed; six logical cells each128 independent chains x64 origins. Long-burn primaries were specified before execution: L8burn512 andL16burn2048. No replacements or coverage changes. Earlier authorization arrived while the agent was completed; STARTED.json records the subsequent explicit-resume launch rather than implying earlier execution.', '', f"Actual subprocess wall {sum(r['seconds'] for r in status):.6f}s, plus {forecast['micros']:.6f}s prior micros. Maximum subprocess wall {max(r['seconds'] for r in status):.6f}s; maximum reported RSS {max(json.loads((p/(r['name']+'.json')).read_text())['rss_mib'] for r in status):.6f}MiB. These are measured runtime receipts, not asymptotic efficiency claims.", '', '|L|burn|h|alpha|r|SE|a|C plugin|precision|','|---|---|---|---|---|---|---|---|---|']
for c in x['cells']:
 for r in c['rows']:
  lines.append(f"|{c['L']}|{c['burn']}|{r['harmonic']}|{r['alpha']:.7g}|{r.get('r',float('nan')):.8g}|{r.get('r_SE',float('nan')):.4g}|{r.get('a',float('nan')):.8g}|{r.get('C_plugin',float('nan')):.8g}|{r.get('precision_nominal',False)}|")
rows=[r for c in x['cells'] for r in c['rows']];com=x['burn_comparisons'];flags=[r for r in com if r['flag']]
lines += ['',f"Precision4SE<=10%r passes{sum(r.get('precision_nominal',False) for r in rows)}/{len(rows)} rows; valid positive pooled responses{sum(r['valid'] for r in rows)}/{len(rows)}. Burn-control comparisons flagged{len(flags)}/{len(com)} at4SE. These nominal diagnostics are not simultaneous confidence bounds or a stationarity certificate. Unflagged differences do not prove equilibration.", '', 'Flagged burn comparisons: '+json.dumps(flags), '', 'The ideal geometric elementary-step estimator is a finite-regulator resolvent. Contributions above the predeclared cap are zeroed, not redrawn or replaced by capped endpoints. The small-rational certificate bounds ideal stationary clipping error by .001. Floating uniform/logarithm generation is not an exact probability oracle; no rigorous sampling-error enclosure is claimed. Finite-burn and regulator effects remain distinct from this clipping bound.', '', 'Minimum-q regulators scale with qhat²/2; matched-q regulators remain .25,.5,1. All joint Nf/S/Y chain means, full sample covariance and a/r/b/C influence covariance are in ANALYSIS.json. Every raw complex origin/product, Nf, lag and clipping flag is in per-chain NPZ files. Averages use chains as independent units, not individual origins or channels.', '', 'C=(a+alpha)r>=1 and Delta_supported<=1/r-alpha<=a are exact-measure inequalities on the declared component, not certified bounds for the plug-in estimates. Large regulator can make C close to1 trivially. No dispersion exponent, pole, photon or continuum claim is inferred. The previous14/18 precision pilot remains unchanged.', '', 'PRODUCTION_FINAL_HASHES.json binds current code, dependencies, analysis, status, report and every raw shard artifact. No further runs were launched.']
(p/'PRODUCTION_REPORT.md').write_text('\n'.join(lines)+'\n')
files=['stream.py','analyze.py','launch.py','PRODUCTION_FREEZE.json','DEPENDENCIES.json','PRODUCTION_PROTOCOL.md','CAP_SUPPLEMENT.md','ANALYSIS.json','STATUS.json','STARTED.json','PRODUCTION_REPORT.md','PRODUCTION.stdout','PRODUCTION.stderr']
for s in status:
 files += [s['name']+'.json',s['name']+'.stderr']+[str(f.relative_to(p)) for f in sorted((p/s['name']).glob('*.npz'))]
(p/'PRODUCTION_FINAL_HASHES.json').write_text(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in files},indent=2)+'\n')
print(lines[-8:])
