#!/usr/bin/env python3
"""Fixed Wilson words in supplied NN SU(2) matrices.
Uniform face/body identities and a small-parameter diagnostic are checked.
A fixed word adds no independent transporter variable. It does not exclude
new actions or couplings using that word, or supply physical dynamics.
"""

from __future__ import annotations

from itertools import permutations
from pathlib import Path

import numpy as np
from scipy.linalg import expm, logm

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTE = REPO_ROOT / "docs" / "DIAGONAL_AS_WILSON_LINE_COMPOSITE_L1_NEGATIVE_NOTE_2026-06-04.md"


AUDIT_INPUT_PATHS = ('docs/DIAGONAL_AS_WILSON_LINE_COMPOSITE_L1_NEGATIVE_NOTE_2026-06-04.md', 'docs/MINIMAL_AXIOMS_2026-06-29.md')
INPUT_SHA256 = {'docs/DIAGONAL_AS_WILSON_LINE_COMPOSITE_L1_NEGATIVE_NOTE_2026-06-04.md': '61452036375917b5b1f589df65d306a3c01e776703f88c63c4c6f6fd3cbaed20', 'docs/MINIMAL_AXIOMS_2026-06-29.md': '93af34cf6fcfcfcc85c2cd39e8be7bbcf25253030f83a4cbc905a4a0cd68b753'}


def require_inputs():
    """Fail before science if the current publication/premise bytes have drifted."""
    import hashlib
    for relative in AUDIT_INPUT_PATHS:
        path = REPO_ROOT / relative
        if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != INPUT_SHA256[relative]:
            print(f"INPUT_MISMATCH {relative}")
            return False
    return True

PASS = 0
FAIL = 0


def record(label: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
        print(f"PASS {label}" + (f" :: {detail}" if detail else ""))
    else:
        FAIL += 1
        print(f"FAIL {label}" + (f" :: {detail}" if detail else ""))


def close(a, b, atol=1e-11):
    return np.allclose(a, b, atol=atol)


SX = np.array([[0, 1], [1, 0]], dtype=complex)
SY = np.array([[0, -1j], [1j, 0]], dtype=complex)
SZ = np.array([[1, 0], [0, -1]], dtype=complex)
EYE = np.eye(2, dtype=complex)


def su2(axis, angle):
    """exp(i * angle * (axis . sigma)/2) in SU(2), |axis| normalized."""
    n = np.array(axis, dtype=float)
    n = n / np.linalg.norm(n)
    A = (n[0] * SX + n[1] * SY + n[2] * SZ) / 2.0
    return expm(1j * angle * A)


def is_su2(U):
    return close(U.conj().T @ U, EYE) and abs(np.linalg.det(U) - 1) < 1e-10


def plaquette(Ua, Ub):
    """Standard ordered Wilson plaquette U_a U_b U_a^{-1} U_b^{-1}."""
    return Ua @ Ub @ np.linalg.inv(Ua) @ np.linalg.inv(Ub)


def main() -> int:
    if not require_inputs():
        return 2
    print("=" * 72)
    print("L1 diagonal = Wilson-line composite of NN connections")
    print("=" * 72)

    # ---- non-commuting NN sample connection (uniform background) ----------
    Ux = su2([1, 0, 0], 0.7)
    Uy = su2([0, 1, 0], 1.1)
    Uz = su2([0, 0, 1], 0.9)
    for name, U in [("U_x", Ux), ("U_y", Uy), ("U_z", Uz)]:
        record(f"NN link {name} is in SU(2)", is_su2(U))
    record("sample U_x and U_y do NOT commute (curved background)", not close(Ux @ Uy, Uy @ Ux))

    # ---- face-diagonal (1,1,0): two NN paths ------------------------------
    # path A: +x then +y ;  path B: +y then +x   (operator order = last step on left)
    W_A = Uy @ Ux
    W_B = Ux @ Uy
    record("face-diagonal path-A holonomy U_y U_x is in SU(2)", is_su2(W_A))
    record("face-diagonal path-B holonomy U_x U_y is in SU(2)", is_su2(W_B))
    record("the two diagonal paths disagree (path-dependent holonomy)", not close(W_A, W_B))

    # headline: the difference of the two path holonomies IS the plaquette F_xy
    P_xy = plaquette(Ux, Uy)
    record(
        "W_B W_A^{-1} equals the plaquette P_xy = U_x U_y U_x^-1 U_y^-1 (field strength)",
        close(W_B @ np.linalg.inv(W_A), P_xy),
    )
    record("P_xy is in SU(2)", is_su2(P_xy))
    record("the diagonal holonomy carries no parameter beyond {U_x,U_y}: W_A is exactly U_y@U_x",
           close(W_A, Uy @ Ux))

    # both diagonal holonomies live in the group generated by the NN links:
    # W_A, W_B are words in U_x, U_y only -> no new generator.
    record("both face-diagonal holonomies are words in NN links only (no independent word variable)",
           close(W_A, Uy @ Ux) and close(W_B, Ux @ Uy))

    # ---- flat / commuting NN background: path-independence ----------------
    # abelian sample (all generated by sigma_z) -> all plaquettes trivial
    Vx = su2([0, 0, 1], 0.5)
    Vy = su2([0, 0, 1], 1.3)
    Vz = su2([0, 0, 1], 0.2)
    record("abelian sample V_x, V_y commute", close(Vx @ Vy, Vy @ Vx))
    record("abelian plaquette P_xy is trivial (identity)", close(plaquette(Vx, Vy), EYE))
    record("with trivial plaquette the two face-diagonal paths AGREE (the tested paths agree)",
           close(Vy @ Vx, Vx @ Vy))

    # ---- plaquette = field strength: leading order is the commutator ------
    a = 1e-3
    Ax = (SX) / 2.0
    Ay = (SY) / 2.0
    Uxs = expm(1j * a * Ax)
    Uys = expm(1j * a * Ay)
    P_small = plaquette(Uxs, Uys)
    logP = logm(P_small)
    leading = -(a ** 2) * (Ax @ Ay - Ay @ Ax)  # group commutator -> -a^2 [Ax,Ay]
    resid = np.linalg.norm(logP - leading)
    record(
        "one a=1e-3 diagnostic of log(plaquette) + a^2 [A_x,A_y] = O(a^3)",
        resid < 50 * a ** 3,
        f"resid={resid:.2e} vs a^3={a**3:.2e}",
    )
    record("the supplied plaquette commutator [A_x,A_y] is nonzero",
           not close(Ax @ Ay - Ay @ Ax, np.zeros((2, 2))))

    # ---- body-diagonal (1,1,1): six orderings -----------------------------
    links = {"x": Ux, "y": Uy, "z": Uz}
    orderings = list(permutations("xyz"))
    record("body-diagonal has 3! = 6 NN path orderings", len(orderings) == 6)
    holos = {}
    for order in orderings:
        # operator order: first step rightmost
        W = EYE.copy()
        for step in order:
            W = links[step] @ W
        holos[order] = W
    record("all 6 body-diagonal holonomies are in SU(2)", all(is_su2(W) for W in holos.values()))

    # in a curved background the 6 holonomies are distinct
    distinct = {tuple(np.round(W.ravel(), 8)) for W in holos.values()}
    record("curved background: the 6 body-diagonal holonomies are not all identical",
           len(distinct) > 1, f"{len(distinct)} distinct")

    # every pair differs by a product of face-plaquette holonomies:
    # adjacent transpositions in the ordering = a single plaquette insertion.
    # Check the displayed adjacent-swap relation explicitly.
    Pxy = plaquette(Ux, Uy)
    Pyz = plaquette(Uy, Uz)
    Pxz = plaquette(Ux, Uz)
    # W for order (z,y,x) read right-to-left = Ux Uy Uz ; swapping the last two NN
    # steps (x<->y) multiplies by a (conjugated) plaquette. Verify the ratio of
    # any two orderings lies in the group generated by face plaquettes by showing
    # it is built from {Pxy,Pyz,Pxz} and NN conjugates -> here we verify the two
    # orderings that differ by swapping the FIRST two steps differ by a plaquette.
    W_xy = Uz @ Uy @ Ux       # order x,y,z (x first)
    W_yx = Uz @ Ux @ Uy       # order y,x,z (y first)
    record(
        "swapping first two body-diagonal steps multiplies holonomy by plaquette P (=field strength)",
        close(W_xy @ np.linalg.inv(W_yx), Uz @ plaquette(Uy, Ux) @ np.linalg.inv(Uz)),
    )

    # flat background: all 6 body-diagonal holonomies coincide (path-independent)
    vlinks = {"x": Vx, "y": Vy, "z": Vz}
    vholos = []
    for order in orderings:
        W = EYE.copy()
        for step in order:
            W = vlinks[step] @ W
        vholos.append(W)
    record("flat background: all 6 body-diagonal holonomies coincide (the tested paths agree)",
           all(close(vholos[0], W) for W in vholos))
    record("flat background: face-plaquettes P_xy,P_yz,P_xz all trivial",
           close(plaquette(Vx, Vy), EYE) and close(plaquette(Vy, Vz), EYE) and close(plaquette(Vx, Vz), EYE))

    # Fixed words do not select an action coefficient: a concrete contrast.
    trace_word = float(np.trace(W_A).real)
    record("changing kappa changes kappa Re Tr(W_A) while W_A stays fixed",
           abs(2.0 * trace_word - trace_word) > 1e-9 and close(W_A, Uy @ Ux))

    # ---- source-note firewalls --------------------------------------------
    if NOTE.exists():
        text = " ".join(NOTE.read_text(encoding="utf-8").split())  # whitespace-robust
        for phrase in [
            "fixed Wilson word adds no independent connection variable",
            "fully determined by the NN connection variables",
            "does not change axioms",
        ]:
            record(f"publication text check: {phrase!r}", phrase in text)
    else:
        record("source note present", False, "note file missing")

    print("=" * 72)
    print(f"SUMMARY: PASS={PASS} FAIL={FAIL}")
    print(f"TOTAL: {PASS} passed, {FAIL} failed")
    print("=" * 72)
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
