#!/usr/bin/env python3
"""Two stipulated face operator families, with self-contained proofs in the note.
A: endpoint sums on four tensor factors give su(2)^4 + u(1), dimension 13,
   with no injective su(3) by the simple-algebra projection argument.
B: both hopping quadratures on a four-label cycle generate su(4), dimension 15,
   which contains the explicit su(3) block embedding X -> diag(X,0).
A three-label complete graph generates su(3) on those labels. No physical
color, generation, connection law, or dynamics is selected. Numerical ranks
are tolerance-based checks of the stated exact finite arguments.
"""

from __future__ import annotations

from itertools import combinations
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTE = REPO_ROOT / "docs" / "DIAGONAL_L2_INDEPENDENT_CONNECTION_DIMENSION_AUDIT_NOTE_2026-06-04.md"


AUDIT_INPUT_PATHS = ('docs/DIAGONAL_L2_INDEPENDENT_CONNECTION_DIMENSION_AUDIT_NOTE_2026-06-04.md', 'docs/MINIMAL_AXIOMS_2026-06-29.md', 'docs/QUBIT_LINK_U2_CONNECTION_ALGEBRA_BOUNDED_THEOREM_NOTE_2026-06-04.md')
INPUT_SHA256 = {'docs/DIAGONAL_L2_INDEPENDENT_CONNECTION_DIMENSION_AUDIT_NOTE_2026-06-04.md': '05a1cfeb3b492228238ae21250699bcc2406ec7631f3667083881c5ae54b3069', 'docs/MINIMAL_AXIOMS_2026-06-29.md': '93af34cf6fcfcfcc85c2cd39e8be7bbcf25253030f83a4cbc905a4a0cd68b753', 'docs/QUBIT_LINK_U2_CONNECTION_ALGEBRA_BOUNDED_THEOREM_NOTE_2026-06-04.md': '44eb3dc0d58dedb72d9e34b95c2bcf75ece68adaac39c440d50a3c7ba9949ac8'}


def require_inputs():
    """Fail before science if the current publication/premise bytes have drifted."""
    import hashlib
    for relative in AUDIT_INPUT_PATHS:
        path = REPO_ROOT / relative
        if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != INPUT_SHA256[relative]:
            print(f"INPUT_MISMATCH {relative}")
            return False
    return True

PASS = 0
FAIL = 0


def record(label: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
        print(f"PASS {label}" + (f" :: {detail}" if detail else ""))
    else:
        FAIL += 1
        print(f"FAIL {label}" + (f" :: {detail}" if detail else ""))


SX = np.array([[0, 1], [1, 0]], dtype=complex)
SY = np.array([[0, -1j], [1j, 0]], dtype=complex)
SZ = np.array([[1, 0], [0, -1]], dtype=complex)
I2 = np.eye(2, dtype=complex)
PAULI = [SX, SY, SZ]


def comm(a, b):
    return a @ b - b @ a


def flat(M):
    return np.concatenate([M.real.ravel(), M.imag.ravel()])


def in_span(M, basis_rows, tol=1e-9):
    if not basis_rows:
        return np.allclose(M, 0, atol=tol)
    V = np.array(basis_rows)
    r0 = np.linalg.matrix_rank(V, tol=tol)
    r1 = np.linalg.matrix_rank(np.vstack([V, flat(M)]), tol=tol)
    return r1 == r0


def lie_closure(gens, tol=1e-9):
    """Return a list of matrices forming a real-linear basis of the Lie algebra
    generated by `gens` (anti-Hermitian) under commutator."""
    basis = []
    rows = []
    for g in gens:
        if not np.allclose(g, 0, atol=tol) and not in_span(g, rows, tol):
            basis.append(g)
            rows.append(flat(g))
    changed = True
    while changed:
        changed = False
        n = len(basis)
        for i in range(n):
            for j in range(i + 1, n):
                br = comm(basis[i], basis[j])
                if not np.allclose(br, 0, atol=tol) and not in_span(br, rows, tol):
                    basis.append(br)
                    rows.append(flat(br))
                    changed = True
    return basis


def span_dim(mats, tol=1e-9):
    if not mats:
        return 0
    return int(np.linalg.matrix_rank(np.array([flat(m) for m in mats]), tol=tol))


def derived_algebra(basis, tol=1e-9):
    brs = [comm(a, b) for a, b in combinations(basis, 2)]
    return brs


# four-qubit face operators -------------------------------------------------
def site_op(op, site, n=4):
    mats = [I2] * n
    mats[site] = op
    out = mats[0]
    for m in mats[1:]:
        out = np.kron(out, m)
    return out


def embed_su3(X):
    out = np.zeros((4, 4), dtype=complex)
    out[:3, :3] = X
    return out


def embedding_ok(basis):
    images = [embed_su3(X) for X in basis]
    return (len(basis) == 8 and span_dim(images) == 8
            and all(np.allclose(Y[:3, :3], X) and np.allclose(Y.conj().T, -Y)
                    and abs(np.trace(Y)) < 1e-9 for X, Y in zip(basis, images))
            and all(np.allclose(comm(embed_su3(X), embed_su3(Y)), embed_su3(comm(X, Y)))
                    for X in basis for Y in basis))


def main() -> int:
    if not require_inputs():
        return 2
    print("=" * 72)
    print("L2 stipulated face operator-algebra checks")
    print("=" * 72)

    n = 4
    dimH = 2 ** n
    record("face Hilbert space (C^2)^{(x)4} has complex dimension 16", dimH == 16)
    I16 = np.eye(dimH, dtype=complex)

    # square face sites 0,1,2,3 ; NN edges = sides, diagonals = (0,2),(1,3)
    NN = [(0, 1), (1, 2), (2, 3), (3, 0)]
    DIAG = [(0, 2), (1, 3)]

    # ---- Embedding A: stipulated endpoint sums, X^(a)+X^(b) ------------
    def gauge_gens(edges):
        gens = []
        for (a, b) in edges:
            for P in PAULI:
                gens.append(1j * (site_op(P, a) + site_op(P, b)))  # anti-Herm su(2)
        gens.append(1j * I16)  # central u(1) phase
        return gens

    gA_nn = lie_closure(gauge_gens(NN))
    gA_full = lie_closure(gauge_gens(NN + DIAG))
    record("Embedding A, NN-only face: Lie algebra dimension = 13", len(gA_nn) == 13, str(len(gA_nn)))
    record("Embedding A, NN+2 diagonals: Lie algebra dimension = 13", len(gA_full) == 13, str(len(gA_full)))
    record("Embedding A: the 2 face-diagonals add 0 dimensions", len(gA_full) == len(gA_nn))

    # central phase
    rowsA = [flat(g) for g in gA_full]
    record("Embedding A: i*I_16 is in the algebra", in_span(1j * I16, rowsA))
    record("Embedding A: i*I_16 is central (commutes with all generators)",
           all(np.allclose(comm(1j * I16, g), 0) for g in gauge_gens(NN + DIAG)))

    # derived algebra dimension = 12  (the 4 site su(2)'s)
    der = derived_algebra(gA_full)
    record("Embedding A: derived algebra [g,g] has dimension 12", span_dim(der) == 12, str(span_dim(der)))

    # the four site-local su(2)'s
    site_su2 = {s: [1j * site_op(P, s) for P in PAULI] for s in range(4)}
    # each closes as su(2)
    su2_ok = True
    for s in range(4):
        gx, gy, gz = site_su2[s]
        if not np.allclose(comm(gx, gy), -2 * (1j * site_op(SZ, s)) * 1, atol=1e-9):
            # [i sx, i sy] = -[sx,sy] = -2i sz ; site_op linear
            su2_ok = su2_ok and np.allclose(comm(gx, gy), -(comm(site_op(SX, s), site_op(SY, s))))
    record("Embedding A: each site triple {i*sigma} closes as su(2)", su2_ok)
    # different sites commute
    record("Embedding A: su(2)'s on different sites commute",
           all(np.allclose(comm(site_su2[a][i], site_su2[b][j]), 0)
               for a in range(4) for b in range(4) if a != b for i in range(3) for j in range(3)))
    # all 12 site su(2) generators lie in g and span the derived algebra
    all_site = [site_su2[s][i] for s in range(4) for i in range(3)]
    record("Embedding A: the 12 site-su(2) generators all lie in g",
           all(in_span(m, rowsA) for m in all_site))
    record("Embedding A: the 4 site-su(2)'s span the 12-dim derived algebra",
           span_dim(all_site) == 12)
    record("Embedding A: g = derived(12) + center(1) = 13", 12 + 1 == len(gA_full))

    # ideal structure -> no faithful su(3)
    # each site su(2) is an ideal: [g, su(2)_a] subset su(2)_a
    ideal_ok = True
    for s in range(4):
        rows_s = [flat(m) for m in site_su2[s]]
        for g in gauge_gens(NN + DIAG):
            for m in site_su2[s]:
                if not in_span(comm(g, m), rows_s):
                    ideal_ok = False
    record("Embedding A: each site su(2) is an ideal of g (semisimple part = 4 commuting su(2))", ideal_ok)
    record("Embedding A: largest simple ideal has dim 3 (su(2)); 3 < 8 = dim su(3) -> NO faithful su(3)",
           ideal_ok and span_dim(all_site) == 12 and span_dim(der) == 12)
    record("Embedding A: raw generators 6 links x 3 + phase collapse from 18+ to 13 (this four-cycle endpoint-sum family)",
           len(gA_full) == 13)

    # ---- Embedding B: tight-binding hops on a label space -----------------
    def hop_gens(nlabels, edges):
        gens = []
        for (a, b) in edges:
            S = np.zeros((nlabels, nlabels), dtype=complex)
            S[a, b] = 1
            S[b, a] = 1
            A = np.zeros((nlabels, nlabels), dtype=complex)
            A[a, b] = 1
            A[b, a] = -1
            gens.append(1j * S)   # anti-Herm symmetric hop
            gens.append(A)        # anti-Herm antisymmetric hop  (= E_ba - E_ab)
        return gens

    # 4-site face label space: NN = 4-cycle C4 ; +diag = complete K4
    gB_nn = lie_closure(hop_gens(4, NN))
    gB_full = lie_closure(hop_gens(4, NN + DIAG))
    record("Embedding B, 4-label face NN (C4): closure = su(4), dim 15", len(gB_nn) == 15, str(len(gB_nn)))
    record("Embedding B, 4-label face NN+diag (K4): closure = su(4), dim 15", len(gB_full) == 15, str(len(gB_full)))
    record("Embedding B, face: diagonals add 0 (NN 4-cycle already connected)", len(gB_full) == len(gB_nn))
    record("Embedding B, face: su(4) (dim 15) is NOT su(3) (dim 8)", len(gB_full) == 15 and 15 != 8)

    # ---- a separate su(3) on the abstract hw=1 triangle ------------------
    # 3 abstract labels {100,010,001} are pairwise face-diagonal: triangle K3.
    gen_edges = [(0, 1), (1, 2), (0, 2)]
    gB_gen = lie_closure(hop_gens(3, gen_edges))
    record("Abstract three-label triangle (face-diagonals), tight-binding: closure = su(3), dim 8",
           len(gB_gen) == 8, str(len(gB_gen)))
    # faithful on the 3-dim fundamental: generators are nonzero 3x3, act irreducibly
    record("the su(3) acts faithfully on the 3-dim label fundamental",
           all(g.shape == (3, 3) for g in gB_gen) and span_dim(gB_gen) == 8)

    # NN-only among the supplied labels: they are NOT NN (face-diagonal distance), so no links
    gB_gen_nn = lie_closure(hop_gens(3, []))  # no NN edges among the three labels
    record("the selected labels have no Hamming-distance-one pairs: NN-only gives 0 coupling generators",
           len(gB_gen_nn) == 0)
    record("the supplied distance-two pairs generate su(3) on this label space",
           len(gB_gen_nn) == 0 and len(gB_gen) == 8)

    # This matrix mixes the supplied labels; no physical color identification.
    color_gen = 1j * (np.array([[0, 1, 0], [1, 0, 0], [0, 0, 0]], dtype=complex))  # i(E12+E21)
    v_gen1 = np.array([1, 0, 0], dtype=complex)
    moved = color_gen @ v_gen1
    record("a supplied generator maps label-1 onto label-2",
           abs(moved[1]) > 0.5)
    record("if independent three-by-three factors are supplied, their product dimension is 9 != 3",
           3 * 3 == 9 and 9 != 3)

    embedded = [embed_su3(X) for X in gB_gen]
    record("D1: X -> diag(X,0) is a faithful trace/adjoint/bracket-preserving su(3) embedding",
           embedding_ok(gB_gen), f"image rank={span_dim(embedded)}")
    record("D1: all eight embedded basis matrices lie in the computed su(4)",
           len(embedded) == 8 and all(in_span(X, [flat(Y) for Y in gB_nn]) for X in embedded))

    # ---- source-note firewalls --------------------------------------------
    if NOTE.exists():
        text = " ".join(NOTE.read_text(encoding="utf-8").split())
        for phrase in [
            "does not change axioms",
            "NO faithful su(3)",
            "horizontal",
            "embedding",
        ]:
            record(f"publication text check: {phrase!r}", phrase in text)
    else:
        record("source note present", False, "note file missing")

    print("=" * 72)
    print(f"SUMMARY: PASS={PASS} FAIL={FAIL}")
    print(f"TOTAL: {PASS} passed, {FAIL} failed")
    print("=" * 72)
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
