from pathlib import Path
import hashlib,json
p=Path(__file__).resolve().parent
notes={
'GOAL':'Stage one finite static-source theorem: full electric minimum, complete geodesic eigenspace and exact first-order plaquette operator. No repo integration here.',
'ASSUMPTIONS_AND_IMPORTS':'Supplied compact Hamiltonian29, finite open box, external fundamental/antifundamental source spaces with zero rest/kinetic energy. Complete Peter-Weyl/Schur theory and fixed-volume bounded analytic perturbation are mathematical imports. No uniform remainder, dynamical-source derivation or temporal confinement inference.',
'ROUTE_PORTFOLIO':'Root and primary independently derived source normalization, all-representation equality classification and1/18 square-flip coefficient. Primary checks complete small planar fermionic spectra; root checks3D path flips and4096 cube supports. One coherent theorem, not duplicate claims.',
'NO_GO_LEDGER':'Omitting normalized source trace gives wrong1/6 coefficient. Baryonic/branched supports cannot reach equality because a connecting geodesic already consumes the minimum number of nontrivial edges. Every path does not retain energy4L/a at first order: off-axis ground superpositions split. Finite-volume derivative asymptotics do not license exchanging distance and coupling limits.',
'LITERATURE_BRIDGES':'Kogut etal Phys.Rev.D23,2945(1981) accessible abstract explicitly describes Hamiltonian fluctuating strings and a fermion formulation. Full paywalled text was not claimed read; no unavailable quantitative formula is imported. General string construction is prior art, not claimed new.',
'ARTIFACT_PLAN':'Retrospective staging: canonical source and two standalone runners. Both original proof/preregs/raw/checkers and primary cold review are in evidence. Actual strict JSON/default receipts preserve all scientific fields. These are scratch receipts, not canonical repository caches.',
'CLAIM_STATUS_CERTIFICATE':'Type bounded_theorem, conditional-support. One claim depending on29 supplied Hamiltonian. Entire free minimum and first-order finite-volume operator only. No arbitrary-coupling/static confinement, continuum or native matter claim.',
'REVIEW_HISTORY':'Primary independently reviewed root72f606 proof: evidence/primary/ROOT_REVIEW.md. Root review of primaryc83f1583 is pending receipt at staging time. Canonical source inserts missing sqrt(2/(L+1)) sine normalization only, transparently recorded. Port author does not claim independent review of own port.',
'PR_BACKLOG':'Pending root canonical review, remaining crossreview receipt, isolated integration and required actual staged caches/pipeline. No commit or PR made here.',
'TRACE_GATE':'29 supplies K,V. Full spin-network support/center argument proves all-label minimum analytically. Actual Haar normalization supplies1/18. Exact finite matrices support planar/3D indexing; they are not full interacting spectral calculations.',
'STATUS':'READY FOR ROOT PORT REVIEW, pending root crossreview receipt.34 and37 original check payloads match exactly. Both JSON/default canonical runs PASS180sec/180MiB.',
'REVIEW':'See evidence/primary/ROOT_REVIEW.md and PORT_EXECUTION_RECEIPT.json. Frozen proofs remain independent with candidate disclosure. Mechanical port validation is by the port author.',
'HANDOFF':'Integrate with claim-local independent helper mapping, no runtime file dependencies. Run actual execute_and_write_cache and immediately stage .txt stdout. Root review before graph; no generated pipeline performed in scratch.',
'QUEUE':'Root final review and crossreview receipt, isolated integration, actual caches and required validation.',
'OPPORTUNITY_QUEUE':'Volume/separation-uniform charged-versus-neutral remainder is unresolved here and assigned elsewhere. Do not infer it from36 spatial area suppression.',
'N1_N8':'N1 finite open cubic box. N2 supplied static3/bar3 probes. N3 complete representation support, no trial-state-only proof. N4 fixed-volume perturbative remainder. N5 literal five scopes34/37 actual checks. N6 wrong-normalization adverse and geodesic-splitting control. N7 explicit prior-art attribution. N8 no continuum/arbitrary-coupling/temporal confinement claim.'}
for n,t in notes.items():(p/(n+'.md')).write_text('# '+n.replace('_',' ').title()+'\n\n'+t+'\n')
(p/'STATE.yaml').write_text('status: ready_for_root_port_review\nclaim_count: 1\nrepo_edits: false\nroot_crossreview_receipt_pending: true\ncanonical_cache_pending: true\nresource_seconds: 180\nresource_mib: 180\nprimary_checks: 34\nindependent_checks: 37\n')
(p/'PACK_INDEX.md').write_text('# Static-source geodesic staging\n\nOne canonical source in docs and two standalone scripts. evidence/primary and evidence/root preserve independently frozen proofs, preregistrations, raw checks and candidate disclosure. PORT_EXECUTION_RECEIPT binds exact unchanged science payloads34/37 to actual JSON/default runs. Canonical body differs from root72f606 only by explicit normalization of its sine modes. Full protocol files are retrospective indexes. Root crossreview receipt and independent canonical port review remain pending. No repository edits or cache/pipeline claims.\n')
(p/'HASHES.json').write_text(json.dumps({str(f.relative_to(p)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(p.rglob('*')) if f.is_file() and f.name!='HASHES.json'},indent=2)+'\n');print(hashlib.sha256((p/'PACK_INDEX.md').read_bytes()).hexdigest())
