"""Exact rational spectral-pair basis; no numerical eigenproblem."""
from itertools import product
from fractions import Fraction as F
from math import gcd
from functools import reduce
from pathlib import Path
import signal,time,resource,sys,json,hashlib
signal.alarm(180);START=time.monotonic();N=216;LAM=(12,24,36,48);checks=0

def need(x,s):
 global checks
 checks+=1
 if not x:raise ValueError(s)

def dot(a,b):return sum(x*y for x,y in zip(a,b))
def primitive(a):
 d=reduce(gcd,a,0)
 if not d:return a
 a=[x//d for x in a]
 return [-x for x in a] if next(x for x in a if x)<0 else a
vs=list(product(range(6),repeat=3));ix={v:i for i,v in enumerate(vs)};K=[{} for _ in vs];edges=[];inc=[set() for _ in vs]
for v in vs:
 for a in range(3):
  w=list(v);w[a]=(w[a]+1)%6;i,j=sorted((ix[v],ix[tuple(w)]));z=-2*(-1)**sum(v[:a]);need(j not in K[i],'simple');K[i][j]=z;K[j][i]=-z;e=len(edges);edges.append((i,j));inc[i].add(e);inc[j].add(e)
def mul(x):return [sum(z*x[j] for j,z in row.items()) for row in K]
def A(x):return [-z for z in mul(mul(x))]
def projector_numerator(x,l):
 for m in LAM:
  if m!=l:x=[a-m*b for a,b in zip(A(x),x)]
 return x
# Whole operator polynomial, all216 basis columns.
for v in range(N):
 x=[int(i==v) for i in range(N)]
 for l in LAM:x=[a-l*b for a,b in zip(A(x),x)]
 need(not any(x),'degree8 full polynomial')
v,w=edges[0];cut=inc[v]^inc[w];starA={i for e in inc[v]-inc[w] for i in edges[e]};starB={i for e in inc[w]-inc[v] for i in edges[e]}
bridges=[e for e,(i,j) in enumerate(edges) if e not in cut and ((i in starA and j in starB) or(i in starB and j in starA))]
need(len(bridges)==5,'five geometric bridges')
cases=[('adjacent_bridge_'+str(e),cut|{e}) for e in bridges]+[('adjacent_union',cut|set(bridges))]
for d in [(0,0,1),(0,0,3),(0,1,2),(0,2,3),(1,2,2),(2,2,3)]:
 i,j=0,ix[d];es=inc[i]^inc[j]
 if d==(0,0,1):
  aa={k for e in inc[i]-inc[j] for k in edges[e]};bb={k for e in inc[j]-inc[i] for k in edges[e]}
  es|={e for e,(k,l) in enumerate(edges) if e not in es and ((k in aa and l in bb) or(k in bb and l in aa))}
 cases.append(('pair_'+''.join(map(str,d)),es))
projected={}
for _,es in cases:
 for v in {i for e in es for i in edges[e]}:
  for l in LAM:
   if (v,l) not in projected:projected[v,l]=projector_numerator([int(i==v) for i in range(N)],l)
results=[];certificates={}
for name,es in cases:
 support=sorted({i for e in es for i in edges[e]});basis=[];sectors=[]
 for l in LAM:
  pairs=[]
  for v in support:
   r=primitive(projected[v,l])
   for b,kb,d in pairs:
    z=dot(r,b);r=primitive([d*x-z*y for x,y in zip(r,b)])
    kd=l*d;z=dot(r,kb);r=primitive([kd*x-z*y for x,y in zip(r,kb)])
   if not any(r):continue
   kr=mul(r);d=dot(r,r)
   need(mul(kr)==[-l*x for x in r],'paired block identity')
   need(dot(r,kr)==0 and dot(kr,kr)==l*d,'paired Gram')
   for b,kb,dd in pairs:need(dot(r,b)==dot(r,kb)==dot(kr,b)==dot(kr,kb)==0,'sector orthogonality')
   pairs.append((r,kr,d))
  sectors.append({'lambda':l,'rank':2*len(pairs),'blocks':len(pairs)})
  for r,kr,d in pairs:basis.extend([(r,d),(kr,l*d)])
 # Distinct lambda eigenvectors are orthogonal by symmetric A; verify actual vectors too.
 for i,(b,d) in enumerate(basis):
  for c,dd in basis[:i]:need(dot(b,c)==0,'full Gram')
 for v in support:need(sum((F(b[v]*b[v],d) for b,d in basis),F(0))==1,'endpoint containment')
 rank=len(basis);need(rank%2==0,'even rank')
 # Basis generated by polynomial projectors and invariant paired elimination => W inclusion.
 # Endpoint containment plus K closure proves reverse inclusion and exact minimality.
 results.append(dict(name=name,edge_support=sorted(es),endpoints=support,rank=rank,sectors=sectors,active_complex_modes=rank//2,fock_dimension=str(2**(rank//2)),fixed_parity_dimension=str(2**(rank//2-1))))
 certificates[name]=[{'vector':b,'norm_squared':d} for b,d in basis]
 rss=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/(1048576 if sys.platform=='darwin' else 1024);need(rss<384 and time.monotonic()-START<180,'resources')
# Actual wrong-polynomial control: replace final48 by47, full polynomial no longerzero.
x=[int(i==0) for i in range(N)]
for l in (12,24,36,47):x=[a-l*b for a,b in zip(A(x),x)]
need(any(x),'wrong polynomial mutant discriminated')
# Omit the whole paired basis: endpoint containment predicate is actually false.
need(sum((F(0) for _ in []),F(0))!=1,'omitted support span discriminated')
out=Path(__file__).resolve().parent
(out/'BASES.json').write_text(json.dumps(certificates,separators=(',',':'))+'\n')
result=dict(checks=checks,bridges=bridges,cases=results,seconds=time.monotonic()-START,rss_mib=rss,bases_sha=hashlib.sha256((out/'BASES.json').read_bytes()).hexdigest(),scope='exact minimal K-invariant active subspaces only, no coefficient calculation')
(out/'RESULT.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:v for k,v in result.items() if k!='cases'}));print([(c['name'],c['rank'],[s['rank'] for s in c['sectors']]) for c in results])
