from pathlib import Path
import json,hashlib,numpy as np
p=Path(__file__).resolve().parent;a=json.loads((p/'PRODUCTION_ANALYSIS.json').read_text());status=json.loads((p/'PRODUCTION_STATUS.json').read_text());cells=[json.loads((p/(s['cell']+'.json')).read_text()) for s in status];vectors=json.loads((p/'REPLICA_RESPONSE_VECTORS.json').read_text())
lines=['# Source-energy stochastic calibration: all fixed cells completed','',
'The new binary-configuration tilted kernel completed the exact authorized fourteen jobs without replacements, added seeds, source changes or forward suffixes. Primary population2048/source step.02 gives mu=1.6658056404 ±0.0026748461 independent-replica delta SE, versus exact finite-stencil1.6642623381. Both nominal consistency and5% precision criteria pass. This demonstrates a finite L2 calibration, not unbiasedness, a rigorous confidence level, a positive-excitation identity or a photon phase.','',
'## Frozen provenance and resources','',
'Production used kernel396c74a04271990477bcf2eb3f88dae967f8fb24f531071c3f436c9679487d21, driverdd47a50492354b532795eb4fdd70e8ebbd16267eb3d24073f991f786a8fd9bca, analyzer11349daeed5c2f1ac55cd4ee26184aec061f5fb54dc762f33654d8a7896b2118 and protocolac19207026950b1406551437bfc101e1cfbefae88399fbf805f63ce1303fbf70. Native independent full-code review preceded launch; root separately authorized600seconds production. No code changed after that review.','',
'Production took %.6f seconds inside children, %.6f seconds with subprocess overhead; maximum RSS%.3fMiB. Every job satisfied180seconds/384MiB and total remained below600seconds. Earlier deterministic verification4.539seconds/251.47MiB is separate, not counted as production. All224 source-replica records are retained, representing32 independent paired seven-source vectors, not224 independent response estimates. Each contains all40 Nf/X/physical-energy samples and source shift.'%(sum(c['seconds'] for c in cells),sum(s['seconds'] for s in status),max(c['rss_mib'] for c in cells)), '',
'Every recorded energy obeys (V-1)meanNf+lambda meanX; the scalar shift is restored separately for every source. Every final state/count/Gauss/flux check passes. Cached Fourier drift against literal recalculation during each final40 window is zero in these runs. Minimum resampling-weight effective-population fraction is%.6f; this is NOT an energy ESS. Minimum initial-ancestor fraction after burn is%.6f. Neither diagnostic certifies estimator precision.'%(min(r['ESS']/c['population'] for c in cells for r in c['replicas']),min(r['ancestral_diversity'] for c in cells for r in c['replicas'])), '',
'## All response estimates','',
'|Population|source h|B ± SE|T=dE/dlambda ± SE|mu ± SE|exact finite-stencil mu|nominal consistency / precision|','|---|---|---|---|---|---|---|']
for pop,result in a['populations'].items():
 for r in result['moments']:
  lines.append('|%s|%.2f|%.8f ± %.8f|%.8f ± %.8f|%.8f ± %.8f|%.8f|%s / %s|'%(pop,r['h'],r['kinetic_mean'],r['kinetic_SE'],r['source_derivative_mean'],r['source_derivative_SE'],r['value'],r['SE'],r['exact_finite_stencil'],r['consistency_nominal'],r['precision_nominal']))
lines += ['',
'All four nominal tests pass without changing the primary step. There are zero nonpositive replica source derivatives and zero negative replica B. The smallest T is2.35953369 (population1024,step.01). Positive derivatives still have sampling error; valid=True is not a guarantee. All raw per-replica B,T and source secants, including adverse secants, are explicitly preserved in REPLICA_RESPONSE_VECTORS.json.','',
'Population1024 minus2048 primary difference is−.0030055459 with independent combined SE.0037649842, unflagged. The paired step differences are−.0051588140±.0072220390 and−.0042995996±.0054599894 at1024/2048. Non-detection is not convergence or a bound on population/step bias. In particular doubling population did not reduce the estimated primary SE in this finite set of16 replicas.','',
'## Noisy secants remain adverse evidence','',
'|Population|h|mean forward secant|mean backward secant|replicas with reversed endpoints|','|---|---|---|---|---|']
for pop,rows in vectors.items():
 for j,h in enumerate([.02,.01]):
  lo=np.array([r['sources'][j]['forward_secant'] for r in rows]);hi=np.array([r['sources'][j]['backward_secant'] for r in rows]);lines.append('|%s|%.2f|%.9f|%.9f|%d/16|'%(pop,h,lo.mean(),hi.mean(),sum(lo>hi)))
lines += ['',
'Both mean step.01 intervals are reversed. These are noisy energy differences, not certified concavity bounds. The exact energy is concave and its exact secants bracket pure X, but ordinary stochastic endpoints do not inherit deterministic enclosure status. No endpoints were sorted, clipped or relabelled.','',
'## Separate error sources and comparison','',
'The exact source-step.02 denominator bias is7.66325e-5 and the combined fixed V/source stencil moment differs from pure1.6643330523 by−7.07142e-5. At source-step.01 the corresponding combined bias is−3.14354e-5. These finite-difference errors are distinct from stochastic and finite-population errors. The frozen deterministic last40-of80 window check is below5e-15 in floating arithmetic; it is not a finite-population claim. Ratio uncertainty uses full paired seven-dimensional energy covariance, not independent-source or independent-sweep SEs.','',
'The earlier independent F6 denominator method reported population2048 moment1.660881897±.002557398 SE versus its different finite-stencil/F6 target1.664314691. This fresh two-response run has similar observed precision, but uses different seeds and fourteen rather than ten cells and a different diagonal probe kernel. This is descriptive context, not a paired improvement or an efficiency theorem. No earlier V samples were reused.','',
'## What was gained and what remains','',
'Both numerator and denominator are now inferred from ground-energy responses using actual binary transitions. No forward genealogy enters the denominator estimator, and no pointwise ground-wavefunction ratio is supplied. The price is a supplied nonlocal diagonal source and additional finite differences. Finite-population, burn, response and ratio errors still require control; larger volumes and spectral concentration are untested. The uncentered X can include elastic mass on other components. This packet authorizes no further job.']
(p/'PRODUCTION_REPORT.md').write_text('\n'.join(lines)+'\n')
(p/'PRODUCTION_FINAL_HASHES.json').write_text(json.dumps({x.name:hashlib.sha256(x.read_bytes()).hexdigest() for x in sorted(p.iterdir()) if x.is_file() and x.name!='PRODUCTION_FINAL_HASHES.json'},indent=2)+'\n')
