from pathlib import Path
import hashlib,json,subprocess,datetime
E=Path(__file__).resolve().parent;R=Path('/Users/jonreilly/Projects/Physics');P=Path('/Users/jonreilly/Projects/Physics-worktrees/toe-campaign-planning-20260907')
N='docs/THIRD_PAIR_SHADOW_DERIVED_RC3_OPEN_CYCLE930_BOUNDED_THEOREM_NOTE_2026-07-28.md';S='scripts/frontier_cycle930_third_pair_rc3_2026_07_28.py';I='scripts/frontier_cycle930_third_pair_rc3_independent_check_2026_07_28.py'
b=json.loads((E/'SOURCE_BINDING.json').read_text());h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
findings=[
 {'id':'F1','priority':'P2','title':'Current source and independent-checker closure is not a valid packet','anchors':[{'path':S,'line':119},{'path':I,'line':91},{'path':N,'line':181}],'finding':'Both producers declare tuple(sorted(PINS)), rejected by the actual literal input parser. With all surviving current inputs present, both source checks return runner_declared_inputs_invalid and both original copied caches return input_mismatch. Both real helper APIs find46 inherited static modules but omit the named independent checker. The21 union pins include absent922/889/881 inputs and superseded891/879 bytes; own-note and current memo are not bound.','repair':'Preserve original inputs and historical results, retain only explicitly justified current execution/proof closure, declare literal complete inputs and guard own note/current premises. Include the independent checker through both actual note-derived consumers. Do not overwrite corrected main parents or make a historical controller campaign active authority merely to satisfy old pins. A self-contained finite station/detector packet is a possible narrow repair.','evidence':['ACTUAL_CONSUMERS_COMPLETE_OVERLAY.json','PIN_CLOSURE.json','FINAL_INPUT_CLOSURE.json']},
 {'id':'F2','priority':'P2','title':'Last-clean detector tail is conflated with whole-stretch tail','anchors':[{'path':S,'line':561},{'path':S,'line':638},{'path':I,'line':479},{'path':I,'line':650},{'path':N,'line':111},{'path':I,'line':990}],'finding':'The detector and R3 refusal use last=mask.bit_length()-1 (last clean tick); the checker predictor uses last=length-1 (whole stretch end). Its F1=.1347 and recall=.5311 therefore do not qualify the same R3 component. The note repeatedly describes terminal ticks of the stretch. Exact original component functions accept period2 for clean ticks0,2,...,14 in length18, while that stretch terminal five-tick window is not period2-exact.','repair':'Define and name the original last-clean convention explicitly. Separate the historical whole-stretch feature and score from R3, or recompute only a genuinely matching score on justified retained data. Preserve original numeric evidence rather than silently relabeling it as a different operand. R2 is likewise distance to last clean, not simply declared stretch length; refusal counts are shape-incidence counts.','evidence':['controls.stdout','CONTROL_EXECUTION.json','HISTORICAL_EVIDENCE_SUMMARY.json']},
 {'id':'F3','priority':'P2','title':'Finite failures do not prove an arithmetic impossibility or the cause of zero episodes','anchors':[{'path':N,'line':30},{'path':N,'line':204},{'path':N,'line':214},{'path':N,'line':221},{'path':N,'line':225}],'finding':'The note concludes no function of(B,b)/nothing in the lane arithmetic can close RC3, that the best statistic anyone can build from widths is mediocre, and that the shadow causes the zero. Only six specified features and finite supplied-controller corpora were tested; the text itself correctly labels TP4 measured, not derived. Station crossing of another row is not by itself an actual earlier Record/readout.','repair':'Retain TP1–TP3 station geometry, historical finite counts, the tested equal-width counterexamples and stable-periodicity identity. Withdraw unrestricted arithmetic-exhaustiveness, causal-zero and physical realization/clock implications absent a further proof. Explicitly separate this finite controller/detector from current Record formation/readout and kinetic-isotropy primitive authority. Keep B8/B9 nonblind and B>=10 unbuilt. Carry the odd/even extra-row exception consistently in active summaries.','evidence':['PROOF_REVIEW.md','controls.stdout','HISTORICAL_EVIDENCE_SUMMARY.json']},
 {'id':'F4','priority':'P2','title':'The claimed nonconsecutive widening tooth does not exercise that distinction','anchors':[{'path':I,'line':1244},{'path':I,'line':1265}],'finding':'The plant adds t1+3 to an existing dirty run at t1,t1+1,t1+2, extending that run. The original receipt explicitly records strict_definition_also_sees_it=true; fires only checks wide_hit. The actual statement block reproduces that false-positive control.','repair':'Use an actually separated intervening dirty run and require wide_hit AND NOT strict_hit. The bounded t1+4 control already witnesses this distinction; a widened-to-strict source fault must fail the relevant test. Preserve the original all-green result as historical flawed validation.','evidence':['controls.stdout','HISTORICAL_EVIDENCE_SUMMARY.json']}
]
for row in findings:
 for a in row['anchors']:
  p=E/'originals'/a['path'];a['line_text']=p.read_text().splitlines()[a['line']-1];a['source_sha256']=h(p)
(E/'FINDINGS.json').write_text(json.dumps(findings,indent=2)+'\n')
(E/'PROOF_REVIEW.md').write_text('''# Independent mathematics and evidence boundary

For the supplied unpadded station program, take integer B>=3 and 1<=b<=B-2, N=8B-5 and P=8(B-1-b). In increasing order the eight rows are hf(b-1), f(b-1), hf(b), f(b), r(b), hr(b), r(b-1), hr(b-1). Their cyclic gaps are

`2, 3, 2, 8(B-b)-13, 2, 1, 2, 8b-4`.

The two variable gaps are at least3 and4 on that domain. Hence the sole unit gap is hr(b)→r(b-1). Each proposed pair has difference P, precisely the third terminal has a bank-row predecessor, and none of the three first stations does. Also hr(b)-P=5b+1, which is absent from the row list. Solving x+P=y moduloN over the eight affine row formulas leaves the three first stations, with the additional reverse row at b=floor((B-1)/2): r(b-1) for oddB, r(b) for evenB. The independent integer control checks all253 originally stated cells B=3..24; it does not execute a controller or establish a physical interpretation. The used original719 program construction was inspected: it supplies these station ordinals. Its header itself distinguishes them from physical time.

The two detector implementations agree on their last-clean endpoint. With clean ticks0,2,4,6,8,10,12,14 and length18, their exact lifted functions return period2 with transient0, eight events and one residue, and the primary refusal function returns ACCEPT. The whole-stretch tail ending17 fails periodicity because bits14 and16 differ. This is a component-domain counterexample, not a claim that this mask occurs in the frozen controller corpus. It decisively refutes identification of these two implemented observables. In the historical checker table the whole-stretch feature has1,351 false negatives, whereas the genuine last-clean R3 prerequisite cannot have a false negative relative to a detector acceptance. A matching R3 condition need not be sufficient: later minimum-event/nonconstant-residue guards remain distinct.

A P-periodic binary region repeats complete run widths; unequal clipped boundary runs do not refute that identity. Equality of a selected pair's widths alone imposes much less. The historical table contains156 accepted unequal-only cases and the B8.b6 eight refusals (sixR3,twoR6); these remain reported finite evidence, not newly generated measurements. The printed3,311/3,328/252/98 refusal totals count shape incidences, not a partition of unique stretches.

A unique geometric predecessor does not establish the cause of zero detected episodes. The generators have specified Boolean transition words, seeds, token positions, clock masks and finite horizons; those extra operands affect whether a station crossing yields a clean interval and a detector reading. Six weak feature scores do not exclude other arithmetic predictors, and a finite deterministic experiment itself has a well-defined input-to-output map. No physical-time or Record identification follows from that map. The current memo leaves formation probability/rate unsupplied; realized-state and kinetic-isotropy primitives do not grant this controller's station/program/readout bridge.

The original widening tooth extends a dirty run and still tests a consecutive pair. Executing its exact statements reproduces the historical true/true wide/strict result. Separating the inserted run at t1+4 gives true/false on its actual B5,b3 station fixture. No larger hunt or claimed controller reachability is required to expose this test defect.

Both complete final930 producer bodies and the canonical note were read; all three earlier runner deltas were read, preserving the added determinism check, revised checker pins/machine predicates and later predictor qualification. The actual used719 program/step interface, mapped-action boundary, full922 explanatory note and current corrected891 note were examined. All48 static modules and the kernel's seven additional declared-only inputs are source-bound, but their broad historical physical campaigns have not been independently reviewed or accepted here. This is a correction verdict with that explicit closure boundary, not a full acceptance of the legacy tower. No parent producer or original930 campaign ran.
''')
claims=[
 {'scope':'TP1–TP3 station geometry and odd/even exception','disposition':'Useful conditional finite program mathematics; retain self-contained formulas/domain and the exception, without physical clock grant.'},
 {'scope':'TP4 third-pair occurrence/full-configuration/zero counts; strict and widened hunts','disposition':'Preserve complete historical receipts and finite horizon/tier definitions. Zero is reported empirical evidence, not derived causality or an all-B theorem. Correct F4 validation and F2 endpoint semantics.'},
 {'scope':'RC3 Reading A equal-width necessity/sufficiency; failing cells','disposition':'Useful historical finite counterexamples to this specified discriminator. Do not generalize to impossibility of any arithmetic criterion.'},
 {'scope':'RC3 Reading B stable-periodic widths','disposition':'Conditional identity from periodicity with clipped-edge qualification; not an independent physical selector.'},
 {'scope':'Six-feature ranking and binding-component interpretation','disposition':'Preserve original numeric scores under their actual operands/population. F2 and F3 must correct same-observable and exhaustive-best claims.'},
 {'scope':'Restrictions, seals, determinism, teeth and scope/handoff verdicts','disposition':'Keep all original outputs, earlier corrections, nonblindB8/B9 and unbuiltB>=10 disclosures. Hash custody is not experimental independence or physics acceptance. F1/F4 require current executable evidence repair; original long runs are historical.'},
 {'scope':'Inherited922/891/889/881/879/kernel premises and physical realization','disposition':'Historical source preserved and mapped; current corrected891 source must not be overwritten. No broader parent campaign, physical clock/Record bridge or reserved science accepted by this review.'}
]
(E/'CLAIM_DISPOSITIONS.json').write_text(json.dumps(claims,indent=2)+'\n')
(E/'REPORT.md').write_text('''# Original #6000 focused landing review

**CHANGES REQUIRED.** Four material correction groups are source-bound in `FINDINGS.json`. The station geometry is useful; the original current-input package and several conclusions are not ready to land unchanged. No audit or retained-grade verdict is assigned.

The frozen head is `ad6ff6b310dfe356656110375a174e4410b28ea9`, raw firstparent `f65501b1ac77ff1cfdefc899a115e6da48af870a`. Live GitHub confirms OPEN/non-draft and the complete four authored commits. This is eight additions, no authored deletion, with three earlier runner bodies. All eight are absent on reviewed and last verified remote main `e97ff2fd204611f4091c4b664664dba7c263da65`. The complete raw/head/current Git maps preserve every inherited disposition: all20,796 inherited leaves survive exactly at the PR head; relative to current main16,052 are exact,3,311 differ and1,433 are absent. Those inherited differences are not implicitly selected for landing.

**F1 — Input and checker closure.** Both original `tuple(sorted(PINS))` declarations are invalid under the real literal parser; both caches report `input_mismatch`. On an actual-current-source overlay both helper APIs find46 inherited modules but omit the named independent checker. Old pins also require absent or superseded parent bytes. Repair a bounded retained closure, preserve historical material, bind actual note/current premises and register the required checker. Do not restore old parent authority or overwrite current corrected sources to make stale pins pass.

**F2 — Two different tails are treated as one.** The original detector/R3 ends at the last clean tick. The checker predictive feature ends at the end of the supplied stretch. Both original detector implementations accept the period2 prefix witness in `controls.stdout`, while its whole-stretch tail is not period-exact. Thus the quoted F1=.1347 score does not measure the same R3 prerequisite. State the real endpoint and keep the historical scores under their actual definitions; correct active note, runner summaries and derived receipts consistently.

**F3 — Unsupported causal and exhaustive negative conclusions.** The unique unit-gap shadow does not prove that it causes zero detected episodes. Six tested features do not establish that no arithmetic criterion can settle the question, or that no better width statistic exists. Preserve the finite reported negative examples and leave the broader selector open. The current Record/primitive sources do not supply a physical identification for this controller, station tick or detector readout. Preserve the existing nonblindB8/B9 and unbuiltB>=10 limits.

**F4 — Widening tooth is a false-positive distinction test.** Its added tick merely extends the first dirty run, and its own receipt says `strict_definition_also_sees_it=true`. `fires` does not require the strict test to fail. The exact original block reproduces this. A separated intervening run at t1+4 gives a genuine wide-only witness; the repaired relevant test should also reject replacing widened detection with strict detection.

The short proof in `PROOF_REVIEW.md` derives the unique unit-gap from the eight explicit cyclic gaps and preserves the third-pair and exception structure. Complete original note and both final producer bodies, consequential history deltas and necessary local source/premise boundaries were examined. `CLAIM_DISPOSITIONS.json` accounts for the whole original argument, including historical restrictions and open obligations. Full numerical campaign reproduction and the broad46-module physical lineage are explicitly unaccepted, not silently marked reviewed.

One actual component-control process ran once: exit0,0.052553s, sampled peak30,081,024bytes, with a30s watchdog,2GiB RSS ceiling and BLAS1. It exercised the original pure functions/tooth statements plus253 independent integer station cases. These AST lifts are disclosed component checks, not a bypassed original producer run or a fresh cache. The original458.2s/678.2s outputs exceed this review's30s scope and have invalid current inputs; neither producer nor a parent campaign was run. Complete historical caches/receipts remain verbatim. An external API-view path setup error and initial cache-directory setup error are preserved in `REVIEW_INCIDENTS.md`; no science was changed or rerun.

A narrow author can preserve all eight original bodies, three versions and historical counts while publishing self-contained station/detector lemmas, honest finite negative scope and decisive small diagnostics with correct current inputs. Any retained old runtime must have its actual transitive inputs justified; its size/status is not an acceptance grant. Owner reservations#6379/#6858/#6859 remain held transitively. No selected or mapped direct/static/declared source path intersects their named authored science, and no reserved premise is used for the finite proof. Repairs return to this same reviewer for affected confirmation. No main, source, planning, GitHub or audit action occurred.
''')
context_paths=['AGENTS.md','docs/ai_methodology/skills/review-loop/SKILL.md','docs/ai_methodology/SCIENCE_WORKFLOW.md','docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/audit/data/axiom_premise_nodes.json','docs/MINIMAL_AXIOMS_2026-06-29.md','docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md']
context={}
for rel in context_paths:
 p=R/rel;data=subprocess.check_output(['git','show',b['current_main']+':'+rel],cwd=R);assert data==p.read_bytes();context[rel]=h(p)
pins=json.loads((E/'PIN_CLOSURE.json').read_text())
for row in pins['rows']:
 if row['path'].startswith('docs/') and '891' in row['path'].upper():pass
# Current881/891 names need no title inference: bind every current surviving pinned note.
for row in pins['rows']:
 p=R/row['path']
 if row['path'].startswith('docs/') and p.is_file():context[row['path']]=h(p)
planning={p.name:h(p) for p in [P/'AGENTS.md',P/'TOE_SCORECARD.md',P/'CAMPAIGN_STATUS.md',P/'BACKLOG_STATUS.md',P/'OPEN_PR_INVENTORY.json'] if p.is_file()}
(E/'READ_AND_CONTEXT.json').write_text(json.dumps({'source_read':'Complete final note/S/I and all three earlier runner deltas; all original receipt/cache bodies preserved, headline/claim/gate/score/refusal/tooth data inspected; no exhaustive per-array certification.','necessary_context':'Full current memo, registry procedure/data, relevant kinetic-isotropy/realized-state notes, historical922 note and current corrected891 note; used719 program/step and mapped-action boundary. Other static/declared ancestry mapped only, broad physical arguments unaccepted.','skill_applicability':'Current reviewed owner-focused landing contract used; no exhaustive audit quotas or audit authority.','current_source_hashes':context,'planning_hashes':planning,'reviewed_main':b['current_main']},indent=2)+'\n')
(E/'HANDOFF.md').write_text('''Original #6000: CHANGES REQUIRED, four material groups F1–F4. REPORT.md and PROOF_REVIEW.md give the complete focused scope and useful finite mathematics. Exact four-commit/eight-path/three-version identities are in SOURCE_BINDING and FINAL_SOURCE_DISPOSITION; maps and all recovered bytes are retained. Controls ran once under30s/2GiB; no original or parent campaign ran. Root owns any author assignment and integration; preserve original historical outputs and do not overwrite corrected current parents. Same original reviewer remains available for affected corrections.\n''')
print('wrote four findings, seven scope dispositions and compact report')
